SELECT 
	  INV.ID
	, INV.CODE
	, INV.NAME
	, INV.MANAGER_ID
	, TSK.PRNAME
	, TSK.PRPCTCOMPLETE PCT_COMPLT
	, OCT.DTT_TSK_PLANNED PCT_PLAN
FROM 
	INV_INVESTMENTS INV
	INNER JOIN PRTASK TSK ON INV.ID = TSK.PRPROJECTID
	INNER JOIN ODF_CA_TASK OCT ON TSK.PRID = OCT.ID
	LEFT JOIN PRJ_BASELINE_DETAILS BASD ON TSK.PRID = BASD.OBJECT_ID
	INNER JOIN COP_TSK_DAYS_LATE_V TSK_D ON TSK.PRID = TSK_D.TASK_ID
	LEFT JOIN CMN_LOOKUPS_V LOOK ON TSK.PRSTATUS = LOOK.LOOKUP_ENUM AND LOOK.LOOKUP_TYPE = 'prTaskStatus' AND LOOK.LANGUAGE_CODE = 'en'
WHERE 
	TSK.PRISMILESTONE = 0
	AND TSK.PRISKEY = 1
	AND BASD.IS_CURRENT = 1
	AND BASD.OBJECT_TYPE = 'TASK'
	AND INV.CODE = 'PR000005'