SELECT 
	  INV.ID
	, INV.CODE
	, INV.NAME
	, INV.MANAGER_ID
	, INV.SCHEDULE_FINISH
	, INVP.PERCENT_COMPLETE 
	, OCP.DTT_PLANNED
	, IDL.DAYS_LATE
FROM 
	INV_INVESTMENTS INV
	INNER JOIN ODF_CA_PROJECT OCP ON INV.ID = OCP.ID
	INNER JOIN INV_PROJECTS INVP ON INV.ID = INVP.PRID
	INNER JOIN COP_INV_DAYS_LATE_V IDL ON INV.ID = IDL.INVESTMENT_ID
WHERE 
	INV.CODE = 'PR000005'