SELECT 
  INV.ID
, INV.CODE
, INV.NAME
, RRI.PRIORITY_CODE
, RRI.NAME
, RRI.TARGET_RESOLUTION_DATE
, R.FIRST_NAME || ' ' || R.LAST_NAME ASSIGNED_TO
FROM INV_INVESTMENTS INV
LEFT JOIN RIM_RISKS_AND_ISSUES RRI ON INV.ID = RRI.PK_ID
INNER JOIN SRM_RESOURCES R ON RRI.ASSIGNED_TO = R.ID
WHERE INV.CODE = 'PR000005'
AND RRI.TYPE_CODE = 'ISSUE'
AND STATUS_CODE <> 'CLOSED' 
AND STATUS_CODE <> 'RESOLVED'