SELECT
*
FROM
(
	SELECT
	LINHA
	, INV_ID
	, INV_CODE
	, INV_NAME
	, GRAU_RISCO
	, TIPO_ALT
	, TIPO_VIAB
	, MOTIVO
	, SCORE
	, PROCESSO
	, DT_INICIO
	, DT_FIM
	, LEAD_TIME_ATUAL
	, LEAD_TIME_PADRAO
	, CASE
		WHEN DT_FIM IS NULL THEN 'Em Aberto'
		ELSE 'Concluído'
		END STATUS
	, CASE
		WHEN (CONVERT(INT, CONVERT(DATETIME,ISNULL(DT_FIM,CONVERT(VARCHAR(10),GETDATE(),120)))) + 1) - CONVERT(INT,CONVERT(DATETIME,DT_INICIO)) >= 0 THEN 1
		ELSE 0
		END STATUS_LEAD_TIME
	FROM
	(
		SELECT
		T1.LINHA LINHA
		, T1.INV_ID INV_ID
		, T1.INV_CODE INV_CODE
		, T1.INV_NAME INV_NAME
		, T1.GRAU_RISCO GRAU_RISCO
		, T1.TIPO_ALT TIPO_ALT
		, T1.VIAB_TEC TIPO_VIAB
		, T1.OBJETIVO MOTIVO
		, T1.SCORE SCORE
		, T1.PROCESSO PROCESSO
		, T1.INICIO_WF DT_INICIO
		, T2.FIM_WF DT_FIM
		, CASE
			WHEN CONVERT(INT, CONVERT(DATETIME,ISNULL(T2.FIM_WF,CONVERT(VARCHAR(10),GETDATE(),120)))) - CONVERT(INT, CONVERT(DATETIME,T1.INICIO_WF)) = 0 THEN 1
			ELSE (CONVERT(INT, CONVERT(DATETIME,ISNULL(T2.FIM_WF,CONVERT(VARCHAR(10),GETDATE(),120)))) - CONVERT(INT, CONVERT(DATETIME,T1.INICIO_WF))) + 1
			END LEAD_TIME_ATUAL
		, CASE
			WHEN T1.VIAB_TEC = 'Simples' THEN 7
			WHEN T1.VIAB_TEC = 'Completa' THEN 15
			END LEAD_TIME_PADRAO
		FROM
			(

			SELECT DISTINCT
				OPRJ.pr_posicao_proj LINHA
				, INV.ID INV_ID
				, INV.CODE INV_CODE
				, INV.NAME INV_NAME
				, GRAU_RISCO.NAME GRAU_RISCO
				, VIAB_TEC.NAME VIAB_TEC
				, TIPO_ALT.NAME TIPO_ALT
				, OPRJ.obj_objective OBJETIVO
				, OPRJ.pr_score SCORE
				, CPRO.NAME PROCESSO
				, CONVERT(VARCHAR(10),RSTP.START_DATE,120) INICIO_WF
				
			FROM 
				niku.INV_INVESTMENTS INV 
				JOIN niku.BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
				JOIN niku.BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
				JOIN niku.BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
				JOIN niku.BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
				JOIN niku.CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
				JOIN niku.BPM_RUN_STEPS RSTP ON RSTP.PROCESS_INSTANCE_ID = RPRO.ID
				JOIN niku.BPM_DEF_STEPS DSTP ON RSTP.STEP_ID = DSTP.ID
				JOIN niku.CMN_CAPTIONS_NLS CSTP ON DSTP.ID = CSTP.PK_ID AND CSTP.LANGUAGE_CODE = 'pt' AND CSTP.TABLE_NAME = 'BPM_DEF_STEPS'
				JOIN niku.BPM_RUN_STEP_ACTION_RESULTS SAR ON SAR.STEP_INSTANCE_ID = RSTP.ID 
				JOIN niku.BPM_DEF_STEP_ACTIONS DACT ON DACT.ID = SAR.STEP_ACTION_ID
				LEFT JOIN NIKU.ODF_CA_PROJECT OPRJ ON OPRJ.ID = INV.ID
				LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_ALT ON TIPO_ALT.LOOKUP_CODE = OPRJ.pr_tipo_alt_param AND TIPO_ALT.LOOKUP_TYPE = 'PR_TIPO_ALT_PROD_PROJ' AND TIPO_ALT.LANGUAGE_CODE = 'pt'
				LEFT JOIN NIKU.CMN_LOOKUPS_V GRAU_RISCO ON GRAU_RISCO.LOOKUP_CODE = OPRJ.pr_grau_risco AND GRAU_RISCO.LOOKUP_TYPE = 'PR_LKP_GRAU_RISCO' AND GRAU_RISCO.LANGUAGE_CODE = 'pt'	
				LEFT JOIN NIKU.CMN_LOOKUPS_V VIAB_TEC ON VIAB_TEC.LOOKUP_CODE = OPRJ.pr_viab_tec_legal_pe AND VIAB_TEC.LOOKUP_TYPE = 'PR_LKP_DEC_VIAB' AND VIAB_TEC.LANGUAGE_CODE = 'pt'	
			WHERE
				OPRJ.PARTITION_CODE = 'hm_pos_registro'	
				AND CPRO.NAME IN ('PR - Viabilidade Técnica Legal','PR - Viabilidade Técnica Legal - Manual')
				AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
				AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
				AND CSTP.NAME = 'Fila - Avaliação Farmacotécnica'

		)T1
		LEFT JOIN
		(
			SELECT DISTINCT
				OPRJ.pr_posicao_proj LINHA
				, INV.ID INV_ID
				, INV.CODE INV_CODE
				, INV.NAME INV_NAME
				, OPRJ.pr_score SCORE
				, CPRO.NAME PROCESSO
				, ISNULL(CONVERT(VARCHAR(10),RSTP.END_DATE,120),CONVERT(VARCHAR(10),GETDATE(),120))  FIM_WF
				
			FROM 
				niku.INV_INVESTMENTS INV 
				JOIN niku.BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
				JOIN niku.BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
				JOIN niku.BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
				JOIN niku.BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
				JOIN niku.CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
				JOIN niku.BPM_RUN_STEPS RSTP ON RSTP.PROCESS_INSTANCE_ID = RPRO.ID
				JOIN niku.BPM_DEF_STEPS DSTP ON RSTP.STEP_ID = DSTP.ID
				JOIN niku.CMN_CAPTIONS_NLS CSTP ON DSTP.ID = CSTP.PK_ID AND CSTP.LANGUAGE_CODE = 'pt' AND CSTP.TABLE_NAME = 'BPM_DEF_STEPS'
				JOIN niku.BPM_RUN_STEP_ACTION_RESULTS SAR ON SAR.STEP_INSTANCE_ID = RSTP.ID 
				JOIN niku.BPM_DEF_STEP_ACTIONS DACT ON DACT.ID = SAR.STEP_ACTION_ID
				LEFT JOIN NIKU.ODF_CA_PROJECT OPRJ ON OPRJ.ID = INV.ID
				LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_ALT ON TIPO_ALT.LOOKUP_CODE = OPRJ.pr_tipo_alt_param AND TIPO_ALT.LOOKUP_TYPE = 'PR_TIPO_ALT_PROD_PROJ' AND TIPO_ALT.LANGUAGE_CODE = 'pt'
				LEFT JOIN NIKU.CMN_LOOKUPS_V GRAU_RISCO ON GRAU_RISCO.LOOKUP_CODE = OPRJ.pr_grau_risco AND GRAU_RISCO.LOOKUP_TYPE = 'PR_LKP_GRAU_RISCO' AND GRAU_RISCO.LANGUAGE_CODE = 'pt'		
			WHERE
				OPRJ.PARTITION_CODE = 'hm_pos_registro'	
				AND CPRO.NAME IN ('PR - Viabilidade Técnica Legal','PR - Viabilidade Técnica Legal - Manual')
				AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
				AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
				AND CSTP.NAME = 'Execução - Avaliação Farmacotécnica'
		)T2

		ON T1.INV_ID = T2.INV_ID
		
	)FINAL
)FINAL2
WHERE
	 $X{IN,STATUS,status_acomp}
ORDER BY
	LINHA ASC