SELECT
	INV.ID  PROJ_ID
	, INV.CODE PROJ_CODE
	, INV.NAME PROJ_NAME
	, OPRJ.DITV_PS_VPL VPL_PESSIMISTA
	, OPRJ.DITV_MD_VPL VPL_MODERADO
	, OPRJ.DITV_OT_VPL VPL_OTIMISTA

FROM
	INV_INVESTMENTS INV
	LEFT JOIN ODF_CA_PROJECT OPRJ ON OPRJ.ID = INV.ID

WHERE 
	INV.ID = 5058068