SELECT
	INV.ID  PROJ_ID
	, INV.CODE PROJ_CODE
	, INV.NAME PROJ_NAME
	, OPRJ.DITV_PS_PB PB_PESSIMISTA
	, OPRJ.DITV_MD_PB PB_MODERADO
	, OPRJ.DITV_OT_PB PB_OTIMISTA

FROM
	INV_INVESTMENTS INV
	LEFT JOIN ODF_CA_PROJECT OPRJ ON OPRJ.ID = INV.ID

WHERE 
	INV.ID = 5058068