SELECT
	INV.CODE INV_CODE
	, INV.NAME INV_NAME
	, OPRJ.obj_objective OBJETIVO
	, GER.FULL_NAME GERENTE
	, PROP_NEG.FULL_NAME PROP_NEGOCIO
	, PMO.FULL_NAME PMO
	, FIN.FULL_NAME FIN
	, OPRJ.lg_estrutura_org EST_ORG
	, OPRJ.lg_hierar_dep_pe HIE
	, OPRJ.lg_estab ESTAB
	, OPRJ.lg_premi PREM
	, OPRJ.lg_restricoes REST

FROM 
	NIKU.INV_INVESTMENTS INV
	INNER JOIN NIKU.ODF_CA_PROJECT OPRJ ON OPRJ.ID = INV.ID
	INNER JOIN NIKU.SRM_RESOURCES GER ON GER.ID = INV.MANAGER_ID
	INNER JOIN NIKU.SRM_RESOURCES PROP_NEG ON PROP_NEG.ID = OPRJ.npd_bus_owner
	INNER JOIN NIKU.SRM_RESOURCES PMO ON PMO.ID = OPRJ.obj_stakeholder2
	INNER JOIN NIKU.SRM_RESOURCES FIN ON FIN.ID = OPRJ.obj_stakeholder3

WHERE
	INV.CODE =  $P{cod_proj}
	-- PR1041
		
ORDER BY
	INV.CODE ASC