SELECT DISTINCT
	
	INV.CODE
	, INV.NAME PROJETO
	, INV.ID IDPROJETO
	, TSK.PRID ID_TAREFA
	, TSK.PREXTERNALID ID_EXT_TAREFA
	, TSK.PRNAME NOME_TAREFA
	, CONVERT(VARCHAR(10),TSK.PRSTART,120) INICIO_TAREFA
	, CONVERT(VARCHAR(10),TSK.PRFINISH,120) FIM_TAREFA
	, TSK.PRISTASK

FROM 
	NIKU.INV_INVESTMENTS INV 
	INNER JOIN NIKU.PRTASK TSK ON TSK.PRPROJECTID = INV.ID
	INNER JOIN NIKU.ODF_CA_PROJECT ODFPROJ ON ODFPROJ.id = INV.ID
	INNER JOIN NIKU.INV_PROJECTS INVPROJ ON INVPROJ.PRID = INV.ID	

WHERE 
	TSK.PRISTASK = 0														
	AND INVPROJ.IS_TEMPLATE = 0
	AND INV.CODE = 'PR1001'
													
ORDER BY
	INV.CODE ASC
	, TSK.PRID ASC