SELECT DISTINCT
	INV.ID  PROJ_ID
	, INV.CODE PROJ_CODE
	, INV.NAME PROJ_NAME
	, TIPO_IMPACTO.NAME TIPO_IMPACTO
	, DRIVER.ditv_driver_valor DRIVER_VLR
	, CASE
		WHEN DRIVER.ditv_impacto_tipo = 'impacto_financeiro' THEN TIPO_DRIVER_FIN.NAME
		WHEN DRIVER.ditv_impacto_tipo = 'impacto_nao_financeiro' THEN TIPO_DRIVER_NFIN.NAME
		ELSE ''
		END TIPO_DRIVER
	, DRIVER.ditv_captura_driver CAP_DRIVER_VLR
	, DRIVER.ditv_premissas_ganho PREM_GANHO_INC
	, DRIVER.ditv_premissas_gasto PREM_GASTO

FROM
	INV_INVESTMENTS INV
	INNER JOIN odf_ca_ditv_driver_valor DRIVER ON DRIVER.ODF_PARENT_ID = INV.ID
	LEFT JOIN CMN_LOOKUPS_V TIPO_IMPACTO ON TIPO_IMPACTO.LOOKUP_CODE = DRIVER.ditv_impacto_tipo 
			AND TIPO_IMPACTO.LOOKUP_TYPE = 'DITV_VALORACAO_IMPACTO' 
			AND TIPO_IMPACTO.LANGUAGE_CODE = 'pt'
	LEFT JOIN CMN_LOOKUPS_V TIPO_DRIVER_NFIN ON TIPO_DRIVER_NFIN.LOOKUP_CODE = DRIVER.ditv_driver_tipo 
			AND TIPO_DRIVER_NFIN.LOOKUP_TYPE = 'DITV_VALORACAO_DRIVER_NFIN' 
			AND TIPO_DRIVER_NFIN.LANGUAGE_CODE = 'pt'
	LEFT JOIN CMN_LOOKUPS_V TIPO_DRIVER_FIN ON TIPO_DRIVER_FIN.LOOKUP_CODE = DRIVER.ditv_driver_tipo 
			AND TIPO_DRIVER_FIN.LOOKUP_TYPE = 'DITV_VALORACAO_DRIVER_FIN' 
			AND TIPO_DRIVER_FIN.LANGUAGE_CODE = 'pt'
			
WHERE
	INV.ID =  $P{prj_ditv}

ORDER BY
  INV.ID ASC
  , TIPO_IMPACTO.NAME ASC