SELECT
STATUS_FINAL,
STATUS_ORDER,
COUNT(INV_ID) QTD
FROM
(
	SELECT
	INV_ID,
	INV_CODE,
	INV_NAME,
	EXTRA,
	FASE,
	STATUS,
	SCHEDULE_STATUS,
	STATUS_FINAL,
	CASE
		WHEN STATUS_FINAL = 'No Prazo' THEN 10
		WHEN STATUS_FINAL = 'Demanda No Prazo' THEN 20
		WHEN STATUS_FINAL = 'On hold' THEN 30
		WHEN STATUS_FINAL = 'Demanda On hold' THEN 40
		WHEN STATUS_FINAL = 'Atrasado' THEN 50
		WHEN STATUS_FINAL = 'Demanda Atrasada' THEN 60		
		WHEN STATUS_FINAL = 'Cancelado' THEN 70
		WHEN STATUS_FINAL = 'Demanda Cancelado' THEN 80
		WHEN STATUS_FINAL = 'Extra' THEN 90
		WHEN STATUS_FINAL = 'Sem Status' THEN 100
		WHEN STATUS_FINAL = 'Concluído' THEN 110		
		END STATUS_ORDER,
	OWNER
	FROM
	(
		SELECT DISTINCT
		INV_ID,
		INV_CODE,
		INV_NAME,
		EXTRA,
		FASE,
		STATUS,
		SCHEDULE_STATUS,
		CASE
			WHEN FASE IN ('Con') THEN 'Concluído'
			WHEN SCHEDULE_STATUS IS NULL THEN 'Sem Status'
			WHEN EXTRA = 1 THEN 'Extra'
			WHEN FASE IN ('A00','U0','U1','J0') AND STATUS IN ('hon_lkp_cancelada','hon_lkp_cancelado') THEN 'Demanda Cancelada'
			WHEN FASE IN ('A00','U0','U1','J0') AND STATUS IN ('hon_lkp_on_hold') THEN 'Demanda On hold'
			WHEN FASE IN ('A00','U0','U1','J0') AND SCHEDULE_STATUS < 0 THEN 'Demanda Atrasada'
			WHEN FASE IN ('A00','U0','U1','J0') AND SCHEDULE_STATUS >= 0 THEN 'Demanda No Prazo'
			WHEN STATUS IN ('hon_lkp_cancelada','hon_lkp_cancelado') THEN 'Cancelado'
			WHEN STATUS IN ('hon_lkp_on_hold') THEN 'On hold'
			WHEN SCHEDULE_STATUS < 0 THEN 'Atrasado'
			ELSE 'No Prazo' 
			END STATUS_FINAL, 
		CASE 
			WHEN OWNER LIKE 'S - CS' THEN 'CS' 
			WHEN OWNER LIKE 'S - PARTS' THEN 'SP' 
			WHEN OWNER LIKE 'EDB - HDA' THEN 'EDB - HDA' 
			WHEN OWNER LIKE 'HAB - BR - E' THEN 'HAB - E' 
			WHEN OWNER LIKE 'HAB - BR - DB' THEN 'HAB - DB'		
			WHEN SUBSTR(OWNER,0,INSTR(OWNER,' ')-1) = 'TI' THEN 'IT' 
			ELSE SUBSTR(OWNER,0,INSTR(OWNER,' ')-1) 
			END OWNER
		FROM
		(
			SELECT
			INV_ID,
			INV_CODE,
			INV_NAME,
			EXTRA,
			CASE
				WHEN FASE_PRJ = 'Con' THEN FASE_PRJ
				WHEN FASE_SR IS NULL THEN FASE_PRJ
				ELSE FASE_SR
				END FASE,
			SCHEDULE_STATUS,
			STATUS,
			OWNER
			FROM
			(
				SELECT 
					INVI.ID INV_ID,
					INVI.CODE INV_CODE,
					INVI.NAME INV_NAME,
					OCINV.hon_extra EXTRA,
					STAGE_ATU.NAME FASE_PRJ,
					CASE
						WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
						THEN STAGE_RPT.NAME
						ELSE NULL
						END FASE_SR,
					CASE
						WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
						THEN STATUS_RPT.COP_SCHEDULE_STATUS
						ELSE NULL
						END SCHEDULE_STATUS,
					STATUS.LOOKUP_CODE STATUS,
					OWNER.NAME OWNER	
				FROM 
					INV_INVESTMENTS INVI
					LEFT JOIN ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
					LEFT JOIN CMN_LOOKUPS_V STATUS ON STATUS.LOOKUP_CODE = OCINV.hon_status AND STATUS.LANGUAGE_CODE = 'pt' AND STATUS.LOOKUP_TYPE = 'HON_STATUS_INVESTIMENTO'
					LEFT JOIN CMN_LOOKUPS_V STAGE_ATU ON INVI.STAGE_CODE = STAGE_ATU.LOOKUP_CODE AND   STAGE_ATU.LANGUAGE_CODE = 'pt' AND STAGE_ATU.LOOKUP_TYPE = 'INV_STAGE_TYPE' AND STAGE_ATU.PARENT_LOOKUP_CODE = 'hon_hsdm'
					LEFT JOIN CMN_LOOKUPS_V OWNER ON OWNER.LOOKUP_CODE = OCINV.hon_area AND OWNER.LANGUAGE_CODE = 'pt' AND OWNER.LOOKUP_TYPE = 'HON_LKP_AREA'
					LEFT JOIN (SELECT MAX(ID) MAX_ID, ODF_PARENT_ID INV_ID FROM odf_ca_cop_prj_statusrpt WHERE TRUNC(COP_REPORT_DATE,'MONTH') <= TRUNC(ADD_MONTHS($P{data_referencia},-1),'MONTH') AND COP_REPORT_STATUS = 'FINAL' AND HON_TIPO_REL_STATUS = 'mensal' GROUP BY ODF_PARENT_ID) MAX_REPORT ON MAX_REPORT.INV_ID = INVI.ID
					LEFT JOIN odf_ca_cop_prj_statusrpt STATUS_RPT ON MAX_REPORT.MAX_ID = STATUS_RPT.ID 
					LEFT JOIN PFM_INVESTMENTS PFMI ON PFMI.INVESTMENT_ID = INVI.ID
					LEFT JOIN PFM_PORTFOLIOS PFMP ON PFMI.PORTFOLIO_ID = PFMP.ID AND PFMP.IS_ACTIVE = 1
					LEFT JOIN (SELECT MAX(ID) MAX_AUDIT, OBJECT_ID INV_ID from cmn_audits where ATTRIBUTE_CODE = 'stage_code' AND  TRUNC(LAST_UPDATED_DATE,'MONTH') <= TRUNC(ADD_MONTHS($P{data_referencia},-1),'MONTH') GROUP BY OBJECT_ID) MAX_AUDIT ON MAX_AUDIT.INV_ID = INVI.ID
					LEFT JOIN CMN_AUDITS AUD ON AUD.ID = MAX_AUDIT.MAX_AUDIT
					LEFT JOIN CMN_LOOKUPS_V STAGE ON AUD.RAW_VALUE_AFTER = STAGE.LOOKUP_CODE AND STAGE.LANGUAGE_CODE = 'pt' AND STAGE.LOOKUP_TYPE = 'INV_STAGE_TYPE' AND STAGE.PARENT_LOOKUP_CODE = 'hon_hsdm'
					LEFT JOIN CMN_LOOKUPS_V STAGE_RPT ON STAGE_RPT.LOOKUP_CODE = STATUS_RPT.hon_fase_atual AND STAGE_RPT.LANGUAGE_CODE = 'pt' AND STAGE_RPT.LOOKUP_TYPE = 'HON_LKP_FASE_PROJETO'
				WHERE 
					PFMP.ID = $P{portfolio}
					AND INVI.ODF_OBJECT_CODE = 'project'				
			)T1
		)T2
	)T3
	WHERE 
		$X{IN,OWNER,owner}
		AND $X{IN,FASE,fase}
)T4
GROUP BY
	STATUS_FINAL,
	STATUS_ORDER

ORDER BY
	STATUS_ORDER ASC