SELECT
    NAME
	, NOME_RPT
	, DT_RELATORIO
    , NVL(FASE_PLAN,'') || chr(10) || NVL(DT_FASE_PLAN,'') FASE_PLAN 
    , NVL(FASE_ATUAL,'') || chr(10) || NVL(DT_FASE_REAL,'') FASE_ATUAL
    , NVL(FASE_ATUAL,'') || chr(10) || NVL(TARGET,'') TARGET
    , CASE 
		WHEN STATUS = -20 THEN '1'
        WHEN STATUS = -5 THEN '2'        
		WHEN STATUS = 0 THEN '3'
        WHEN STATUS = 5 THEN '4'
        WHEN STATUS = 20 THEN '5'     
        ELSE '0'   
		END STATUS
    , PRINCIP_REAL
    , VARIACAO_PLANO
    , PLANO_ACAO
    , BR
    , AREA_PRJ
FROM
(
	SELECT 
		INVI.NAME,
		INVI.ID INV_ID,
		GER.FIRST_NAME || chr(10) || GER.LAST_NAME BR,
		AREA_PRJ.FIRST_NAME || chr(10) || AREA_PRJ.LAST_NAME AREA_PRJ,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN STATUS_RPT.NAME
			ELSE NULL
			END NOME_RPT,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN STATUS_RPT.COP_REPORT_DATE
			ELSE NULL
			END DT_RELATORIO,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN FASE_ATUAL.NAME
			ELSE NULL
			END FASE_ATUAL,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN FASE_PLAN.NAME
			ELSE NULL
			END FASE_PLAN,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN TO_CHAR(STATUS_RPT.hon_dt_fase_real,'DD/MM/YY')
			ELSE NULL
			END DT_FASE_REAL,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN TO_CHAR(STATUS_RPT.hon_dt_fase_plan,'DD/MM/YY')
			ELSE NULL
			END DT_FASE_PLAN,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN TO_CHAR(STATUS_RPT.hon_target,'DD/MM/YY')
			ELSE NULL
			END TARGET,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN STATUS_RPT.cop_schedule_status
			ELSE NULL
			END STATUS,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN STATUS_RPT.cop_key_accomplish
			ELSE NULL
			END PRINCIP_REAL,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN STATUS_RPT.cop_schedule_exp
			ELSE NULL
			END VARIACAO_PLANO,
		CASE
			WHEN (STATUS_RPT.COP_REPORT_STATUS = 'FINAL' AND STATUS_RPT.HON_TIPO_REL_STATUS = 'mensal')
			THEN STATUS_RPT.cop_upcoming_act
			ELSE NULL
			END PLANO_ACAO
	FROM 
		INV_INVESTMENTS INVI
		JOIN odf_ca_project OCPRJ ON INVI.ID = OCPRJ.ID
		LEFT JOIN (SELECT MAX(ID) MAX_ID, ODF_PARENT_ID INV_ID FROM odf_ca_cop_prj_statusrpt WHERE TRUNC(COP_REPORT_DATE,'MONTH') = TRUNC($P{data_referencia},'MONTH') GROUP BY ODF_PARENT_ID) MAX_REPORT ON MAX_REPORT.INV_ID = INVI.ID
		LEFT JOIN odf_ca_cop_prj_statusrpt STATUS_RPT ON MAX_REPORT.MAX_ID = STATUS_RPT.ID 
		LEFT JOIN CMN_LOOKUPS_V FASE_ATUAL ON FASE_ATUAL.LOOKUP_CODE = STATUS_RPT.hon_fase_atual AND FASE_ATUAL.LANGUAGE_CODE = 'pt' AND FASE_ATUAL.LOOKUP_TYPE = 'HON_LKP_FASE_PROJETO'
		LEFT JOIN CMN_LOOKUPS_V FASE_PLAN ON FASE_PLAN.LOOKUP_CODE = STATUS_RPT.hon_fase_planejada AND FASE_PLAN.LANGUAGE_CODE = 'pt' AND FASE_PLAN.LOOKUP_TYPE = 'HON_LKP_FASE_PROJETO'
		LEFT JOIN SRM_RESOURCES GER ON GER.USER_ID = INVI.MANAGER_ID
		LEFT JOIN SRM_RESOURCES AREA_PRJ ON AREA_PRJ.ID = OCPRJ.hon_area_projetos
	
)	
WHERE 
	INV_ID = $P{INV_ID}