SELECT DISTINCT
	AREA_TI.NAME AREA_TI

FROM
	niku.INV_INVESTMENTS INV
	LEFT JOIN niku.ODF_CA_INV OINV ON OINV.ID = INV.ID
	LEFT JOIN NIKU.CMN_LOOKUPS_V AREA_TI ON AREA_TI.LOOKUP_CODE = OINV.hm_area_ti AND AREA_TI.LOOKUP_TYPE = 'AREAS_TI' AND AREA_TI.LANGUAGE_CODE = 'PT'
	
WHERE
	INV.IS_ACTIVE = 1
	AND AREA_TI.NAME != 'NULL'

ORDER BY 
	AREA_TI.NAME ASC
	