SELECT

GERENTE_EXEC
, SUM(VALOR_SEM_PAGTO) VALOR

FROM
(
	SELECT
	FORNECEDOR
	, PEDIDO_COMPRAS
	, NOME
	, ESPECIALIDADE
	, CODIGO_DESC_PROJETO
	, GERENTE_EXEC 
	, DATA
	, DATENAME(MONTH, DATA) +'-'+ SUBSTRING(CONVERT(VARCHAR(4),DATEPART(yy,DATA)),3,2) PERIODO
	, SUM(HORAS_NORMAIS_PAGO + HORAS_EXTRAS_50_PAGO + HORAS_EXTRAS_100_PAGO) SALDO_HORAS_PAGO
	, SUM(HORAS_NORMAIS_SEM_PAGTO + HORAS_EXTRAS_50_SEM_PAGTO + HORAS_EXTRAS_100_SEM_PAGTO) SALDO_HORAS_SEM_PAGTO
	, SUM(VALOR_NORMAIS_PAGO + VALOR_EXTRAS_50_PAGO + VALOR_EXTRAS_100_PAGO) VALOR_PAGO
	, SUM(VALOR_NORMAIS_SEM_PAGTO + VALOR_EXTRAS_50_SEM_PAGTO + VALOR_EXTRAS_100_SEM_PAGTO) VALOR_SEM_PAGTO


	FROM

	(

	SELECT 
		APM.ADDRESS_NAME FORNECEDOR
		, CONT.hm_pedido_compras PEDIDO_COMPRAS
		, SRES.FIRST_NAME + ' ' + SRES.LAST_NAME NOME
		, FUNC.FULL_NAME ESPECIALIDADE
		, INVI.CODE + '_' + INVI.NAME CODIGO_DESC_PROJETO
		, GER_EXEC.FIRST_NAME + ' ' + GER_EXEC.LAST_NAME GERENTE_EXEC
		, REG.hm_dia DATA
		, (CASE WHEN REG.hm_ponto_val = 1 THEN ISNULL(REG.hm_horas_norm,0) ELSE 0 END) * INVR.hm_pct_horas_trab HORAS_NORMAIS_PAGO
		, (CASE WHEN REG.hm_ponto_val = 0 THEN ISNULL(REG.hm_horas_norm,0) ELSE 0 END) * INVR.hm_pct_horas_trab HORAS_NORMAIS_SEM_PAGTO
		, (CASE WHEN REG.hm_ponto_val = 1 THEN ISNULL(REG.hm_horas_norm,0) ELSE 0 END) * INVR.hm_pct_horas_trab * CONT.hm_valor_hora_normal VALOR_NORMAIS_PAGO
		, (CASE WHEN REG.hm_ponto_val = 0 THEN ISNULL(REG.hm_horas_norm,0) ELSE 0 END) * INVR.hm_pct_horas_trab * CONT.hm_valor_hora_normal VALOR_NORMAIS_SEM_PAGTO
		, (CASE WHEN REG.hm_ponto_val = 1 THEN ISNULL(REG.hm_horas_ex_50,0) ELSE 0 END) * INVR.hm_pct_horas_trab HORAS_EXTRAS_50_PAGO
		, (CASE WHEN REG.hm_ponto_val = 0 THEN ISNULL(REG.hm_horas_ex_50,0) ELSE 0 END) * INVR.hm_pct_horas_trab HORAS_EXTRAS_50_SEM_PAGTO
		, (CASE WHEN REG.hm_ponto_val = 1 THEN ISNULL(REG.hm_horas_ex_50,0) ELSE 0 END) * INVR.hm_pct_horas_trab * (CONT.hm_valor_hora_normal * 1.5) VALOR_EXTRAS_50_PAGO
		, (CASE WHEN REG.hm_ponto_val = 0 THEN ISNULL(REG.hm_horas_ex_50,0) ELSE 0 END) * INVR.hm_pct_horas_trab * (CONT.hm_valor_hora_normal * 1.5) VALOR_EXTRAS_50_SEM_PAGTO
		, (CASE WHEN REG.hm_ponto_val = 1 THEN ISNULL(REG.hm_horas_ex_100,0) ELSE 0 END) * INVR.hm_pct_horas_trab HORAS_EXTRAS_100_PAGO
		, (CASE WHEN REG.hm_ponto_val = 0 THEN ISNULL(REG.hm_horas_ex_100,0) ELSE 0 END) * INVR.hm_pct_horas_trab HORAS_EXTRAS_100_SEM_PAGTO
		, (CASE WHEN REG.hm_ponto_val = 1 THEN ISNULL(REG.hm_horas_ex_100,0) ELSE 0 END) * INVR.hm_pct_horas_trab * (CONT.hm_valor_hora_normal * 2) VALOR_EXTRAS_100_PAGO
		, (CASE WHEN REG.hm_ponto_val = 0 THEN ISNULL(REG.hm_horas_ex_100,0) ELSE 0 END) * INVR.hm_pct_horas_trab * (CONT.hm_valor_hora_normal * 2) VALOR_EXTRAS_100_SEM_PAGTO
	FROM 
		NIKU.SRM_RESOURCES SRES
		JOIN NIKU.PAC_MNT_RESOURCES PMRES 
			ON SRES.ID = PMRES.ID
		JOIN NIKU.APMASTER APM 
			ON APM.VENDOR_CODE = PMRES.VENDOR_CODE
		JOIN NIKU.ODF_CA_HM_CONTRATACAO CONT
			ON CONT.ODF_PARENT_ID = SRES.ID
		JOIN NIKU.PRJ_RESOURCES PRES
			ON PRES.PRID = SRES.ID
		JOIN NIKU.SRM_RESOURCES FUNC
			ON PRES.PRPRIMARYROLEID = FUNC.ID
		JOIN NIKU.ODF_CA_HM_REGISTRO_PONTO REG
			ON REG.hm_recurso = SRES.USER_ID
			AND REG.hm_dia BETWEEN CONT.hm_inicio_vigencia AND CONT.hm_termino_vigencia
		JOIN NIKU.ODF_CA_HM_INV_REG_PONTO INVR
			ON REG.id = INVR.ODF_PARENT_ID
		JOIN NIKU.INV_INVESTMENTS INVI 
			ON INVI.ID = INVR.hm_investimento
		JOIN NIKU.ODF_CA_INV OCINV 
			ON OCINV.ID = INVI.ID
		LEFT JOIN NIKU.SRM_RESOURCES GER_EXEC
			ON GER_EXEC.ID = OCINV.hm_ger_exec_prop
		
	) HORAS


	GROUP BY FORNECEDOR
	, PEDIDO_COMPRAS
	, NOME
	, ESPECIALIDADE
	, CODIGO_DESC_PROJETO
	, DATA
	, GERENTE_EXEC 
)AMTS

WHERE
	GERENTE_EXEC IS NOT NULL
	
GROUP BY
GERENTE_EXEC