SELECT DISTINCT
	
	STATUS_DEM.NAME STATUS_DEM

FROM
	INV_INVESTMENTS INV
	LEFT JOIN ODF_CA_IDEA OIDEA ON OIDEA.ID = INV.ID
	LEFT JOIN CMN_LOOKUPS_V STATUS_DEM ON STATUS_DEM.LOOKUP_CODE = OIDEA.TB_STAT_DEMANDA AND STATUS_DEM.LOOKUP_TYPE = 'TB_STATUS_DEMANDA' AND STATUS_DEM.LANGUAGE_CODE = 'pt'

WHERE
	INV.ODF_OBJECT_CODE = 'idea'
	AND STATUS_DEM.NAME IS NOT NULL

ORDER BY
	STATUS_DEM.NAME ASC