SELECT DISTINCT

DIR_SOLICITANTE

FROM
(

	SELECT

		CASE
			WHEN DIR_SOLICITANTE.NAME = 'Diretoria AF&Pessoas' THEN 'Dir. AF&Pessoas'
			WHEN DIR_SOLICITANTE.NAME = 'Diretoria de Negócios e Soluções' THEN 'Dir. de Neg. e Soluções'
			WHEN DIR_SOLICITANTE.NAME = 'Diretoria de Operações' THEN 'Dir. de Operações'
			WHEN DIR_SOLICITANTE.NAME = 'Diretoria de Relacionamento' THEN 'Dir. de Relacionamento'
			WHEN DIR_SOLICITANTE.NAME = 'Diretoria de Tec. da Informação' THEN 'Dir. de Tec. da Informação'
			WHEN DIR_SOLICITANTE.NAME = 'Diretoria Geral' THEN 'Dir. Geral'        
		END DIR_SOLICITANTE

	FROM
		INV_INVESTMENTS INV
		LEFT JOIN ODF_CA_INV OINV ON OINV.ID = INV.ID
		LEFT JOIN CMN_LOOKUPS_V DIR_SOLICITANTE ON DIR_SOLICITANTE.LOOKUP_CODE = OINV.TB_INV_DIR_SOLIC AND DIR_SOLICITANTE.LOOKUP_TYPE = 'TB_LISTA_DIRETORIAS' AND DIR_SOLICITANTE.LANGUAGE_CODE = 'pt'

	WHERE
		INV.ODF_OBJECT_CODE = 'idea'

)
WHERE
	DIR_SOLICITANTE IS NOT NULL

ORDER BY
	DIR_SOLICITANTE ASC