SELECT DISTINCT

	CLIENTE.NAME CLIENTE

FROM
	INV_INVESTMENTS INV
	LEFT JOIN ODF_CA_INV OINV ON OINV.ID = INV.ID
	LEFT JOIN CMN_LOOKUPS_V CLIENTE ON CLIENTE.LOOKUP_CODE = OINV.TB_CLIENTE_EXTERNO 
		AND CLIENTE.LOOKUP_TYPE = 'TB_LISTA_CLIENTES' 
		AND CLIENTE.LANGUAGE_CODE = 'pt'

WHERE
	CLIENTE.NAME IS NOT NULL

ORDER BY
	CLIENTE.NAME ASC