SELECT DISTINCT
	CATEGORIA.NAME CATEGORIA

FROM
	INV_INVESTMENTS INV
	LEFT JOIN ODF_CA_IDEA OIDEA ON OIDEA.ID = INV.ID
	LEFT JOIN CMN_LOOKUPS_V CATEGORIA ON CATEGORIA.LOOKUP_CODE = OIDEA.OBJ_REQUEST_TYPE AND CATEGORIA.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE' AND CATEGORIA.LANGUAGE_CODE = 'pt'

WHERE
	INV.ODF_OBJECT_CODE = 'IDEA'
	AND CATEGORIA.NAME IS NOT NULL

ORDER BY
	CATEGORIA.NAME ASC
