SELECT 
	INV.CODE CODE
	, TIPO_CUSTO.NAME TIPO_CUSTO
	, TC.DESCRIPTION CLASSE_TRANSACAO
	, CONVERT(DECIMAL,SUM(ISNULL(FPD.TOTAL_COST,0))) CUSTO_PLANEJADO

FROM 
	NIKU.INV_INVESTMENTS INV
	LEFT JOIN NIKU.FIN_PLANS FP ON INV.ID = FP.OBJECT_ID
	LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD ON FP.ID = FPD.PLAN_ID
	LEFT JOIN NIKU.ODF_CA_COSTPLANDETAIL OCP ON FPD.ID = OCP.ID
	LEFT JOIN NIKU.TRANSCLASS TC ON FPD.TRANSACTION_CLASS_ID = TC.ID
	LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RC ON FPD.RESOURCE_CLASS_ID = RC.ID
	LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID 
				AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' 
				AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
	

WHERE 
	FP.IS_PLAN_OF_RECORD=1
	AND INV.CODE = 'PR1016'
	AND TC.DESCRIPTION != ''

GROUP BY 
	INV.CODE
	, TIPO_CUSTO.NAME
	, TC.DESCRIPTION
