SELECT
INV_CODE
, INV_ID
, OBJ_CODE
, INV_NAME
, DIR_EXEC
, DIVISAO
, HIER_PRI
, TIPO_PROJ
, STATUS_PRI
, GUESS_CAPEX
, GUESS_OPEX
, GUESS_REC_INT
, CLASSIFICACAO
, CASE WHEN REP_APROVADA IS NULL THEN (CASE WHEN (CUSTO_ESTIM_EXT)>= 500000 THEN 'Sim' ELSE 'Não' END) ELSE (CASE WHEN (ORC_EXT) >= 500000 THEN 'Sim' ELSE 'Não' END) END MAIOR_500K
, TIPO_CUSTO
, ORC_CAPEX
, ORC_OPEX
, ORC_EXT
, ORC_REC_INT
, GASTO_CAPEX_ANT
, GASTO_OPEX_ANT
, GASTO_EXT_ANT
, GASTO_INT_ANT
, GASTO_CAPEX_ATUAL
, GASTO_OPEX_ATUAL
, GASTO_EXT_ATUAL
, GASTO_INT_ATUAL
, (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL)) DISPONIVEL_EXT
, SITUACAO
, AREA_TI
, PROJ_CAPEX_ATUAL
, PROJ_OPEX_ATUAL
, PROJ_EXT_ATUAL
, PROJ_CAPEX_POST
, PROJ_OPEX_POST
, PROJ_EXT_POST
, CASE 
WHEN (PROJ_EXT_ATUAL + PROJ_EXT_POST) > (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL))  THEN 'Valor projetado acima do Disponível'
WHEN (PROJ_EXT_ATUAL + PROJ_EXT_POST) <= (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL))  THEN 'Valor projetado dentro do Disponível'
ELSE '-' 
END STATUS_ORC


, CASE 
WHEN (PROJ_EXT_ATUAL + PROJ_EXT_POST) > (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL)) 
THEN (PROJ_EXT_ATUAL + PROJ_EXT_POST) - (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL)) 
ELSE 0
END PROJ_NAO_APROV

, CASE 
WHEN (PROJ_EXT_ATUAL + PROJ_EXT_POST) <= (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL)) 
THEN (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL))  - (PROJ_EXT_ATUAL + PROJ_EXT_POST)
ELSE 0
END ORC_NAO_PROJ

, (CASE 
WHEN (PROJ_EXT_ATUAL + PROJ_EXT_POST) <= (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL)) 
THEN (ORC_EXT - (GASTO_EXT_ANT + GASTO_EXT_ATUAL))  - (PROJ_EXT_ATUAL + PROJ_EXT_POST)
ELSE 0
END)/ (ISNULL(NULLIF(ORC_EXT,0),1)) PCT_NAO_PROJ

, GASTO_EXT_ACUM_PROJ 
, GASTO_EXT_ACUM_PROJ - ORC_EXT VARIACAO_PROJ
, (GASTO_EXT_ACUM_PROJ - ORC_EXT)/ISNULL(NULLIF(ORC_EXT,0),1) PCT_ASSERT_PROJ
, CASE WHEN (ABS((GASTO_EXT_ACUM_PROJ - ORC_EXT)/ISNULL(NULLIF(ORC_EXT,0),1)) > 0.2) THEN 'Sim' ELSE 'Não' END DIVER_ASSERT_20

FROM

(
SELECT
INV_CODE
, INV_ID
, OBJ_CODE
, INV_NAME
, DIR_EXEC
, DIVISAO
, HIER_PRI
, TIPO_PROJ
, STATUS_PRI
, GUESS_CAPEX 
, GUESS_OPEX 
, GUESS_REC_INT 
, CUSTO_ESTIM_EXT
, CLASSIFICACAO
, REP_APROVADA
, CASE TIPO_CUSTO WHEN 'Operacional' THEN 'OPEX' ELSE 'CAPEX' END TIPO_CUSTO
, SUM(ISNULL(ORC_CAPEX,0)) ORC_CAPEX
, SUM(ISNULL(ORC_OPEX,0)) ORC_OPEX
, SUM(ISNULL(ORC_CAPEX,0) + ISNULL(ORC_OPEX,0)) ORC_EXT
, SUM(ISNULL(ORC_REC_INT,0)) ORC_REC_INT
, SUM(ISNULL(GASTO_CAPEX_ANT,0)) GASTO_CAPEX_ANT
, SUM(ISNULL(GASTO_OPEX_ANT,0)) GASTO_OPEX_ANT
, SUM(ISNULL(GASTO_CAPEX_ANT,0) + ISNULL(GASTO_OPEX_ANT,0)) GASTO_EXT_ANT
, SUM(ISNULL(GASTO_INT_ANT,0)) GASTO_INT_ANT
, SUM(ISNULL(GASTO_CAPEX_ATUAL,0)) GASTO_CAPEX_ATUAL
, SUM(ISNULL(GASTO_OPEX_ATUAL,0)) GASTO_OPEX_ATUAL
, SUM(ISNULL(GASTO_CAPEX_ATUAL,0) + ISNULL(GASTO_OPEX_ATUAL,0)) GASTO_EXT_ATUAL
, SUM(ISNULL(GASTO_INT_ATUAL,0)) GASTO_INT_ATUAL
, CASE  
WHEN FASE = 'hm_lkp_encerramento' AND SITUACAO = 'hm_sit_encerrado' THEN 'Encerrado'
WHEN FASE IN ('hm_lkp_spgl') THEN 'Entregue'
WHEN SITUACAO IN ('hm_sit_cancelada', 'hm_sit_cance_sol') THEN 'Cancelado'
WHEN SITUACAO IN ('hm_sit_on_hold', 'hm_sit_susp_solicitada') THEN 'On Hold'
WHEN OBJ_CODE = 'idea' OR FASE IN ('hm_aprovar_projeto', 'hm_analisar_projeto') THEN 'Em análise'
ELSE 'A entregar'
END SITUACAO
, AREA_TI
, SUM(ISNULL(PROJ_CAPEX_ATUAL,0)) PROJ_CAPEX_ATUAL
, SUM(ISNULL(PROJ_OPEX_ATUAL,0)) PROJ_OPEX_ATUAL
, SUM(ISNULL(PROJ_CAPEX_ATUAL,0) + PROJ_OPEX_ATUAL) PROJ_EXT_ATUAL
, SUM(ISNULL(PROJ_CAPEX_POST,0)) PROJ_CAPEX_POST
, SUM(ISNULL(PROJ_OPEX_POST,0)) PROJ_OPEX_POST
, SUM(ISNULL(PROJ_CAPEX_POST,0) + ISNULL(PROJ_OPEX_POST,0)) PROJ_EXT_POST
, SUM(ISNULL(GASTO_CAPEX_ANT,0) + ISNULL(GASTO_OPEX_ANT,0) + ISNULL(GASTO_CAPEX_ATUAL,0) + ISNULL(GASTO_OPEX_ATUAL,0) + ISNULL(PROJ_CAPEX_ATUAL,0) + ISNULL(PROJ_OPEX_ATUAL,0) + ISNULL(PROJ_CAPEX_POST,0) + ISNULL(PROJ_OPEX_POST,0)) GASTO_EXT_ACUM_PROJ


FROM
(
-- PROJETOS
SELECT
		
		  INVI.CODE INV_CODE
		, INVI.ID INV_ID
		, INVI.ODF_OBJECT_CODE OBJ_CODE
		, INVI.NAME INV_NAME
		, DIR_EXEC.NAME DIR_EXEC
		, DIVISAO.NAME DIVISAO
		, HIERARQUIA_PRI.NAME HIER_PRI
		, TIPO_PROJ.NAME TIPO_PROJ
		, 'Priorizado ' + CONVERT(VARCHAR(4),OCINV.hm_ano_investimento,126) STATUS_PRI
		, (	
				SELECT 
					OCINV.hm_cust_ext
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON INVI.ID = PMP.ID
				WHERE 
					PMP.COST_TYPE = 'CAPITAL'
					AND OCINV.ID = INVI.IDEA_ID
				
			) GUESS_CAPEX
		, (	
				SELECT 
					OCINV.hm_cust_ext
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON INVI.ID = PMP.ID
				WHERE 
					PMP.COST_TYPE = 'OPERATING'
					AND OCINV.ID = INVI.IDEA_ID
					
			) GUESS_OPEX
		, (	
				SELECT 
					OCINV.hm_cust_int
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON OCINV.ID = PMP.ID
				WHERE 
					 OCINV.ID = INVI.IDEA_ID
			) GUESS_REC_INT
		, CLASSIFICACAO.NAME CLASSIFICACAO
		, OCPRJ.aprovacao_rep REP_APROVADA
		, OCINV.hm_cust_ext CUSTO_ESTIM_EXT
		, TIPO_CUSTO.NAME TIPO_CUSTO
		, 	(	
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') != 'RECINT')
			) ORC_CAPEX
			
		, 	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') != 'RECINT')
			) ORC_OPEX

		, (
			SELECT
				SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
			FROM
				NIKU.FIN_PLANS FIN_PLAN
				LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
				LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
				LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
				LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				
			WHERE
				FIN_PLAN.OBJECT_ID = INVI.ID
				AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
				AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
				AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') = 'RECINT')
			) ORC_REC_INT
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'CAPITAL'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_CAPEX_ANT
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'OPERATING'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_OPEX_ANT

		,	(	
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_INT_ANT
			
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'CAPITAL'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_CAPEX_ATUAL
			
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'OPERATING'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_OPEX_ATUAL
		
		,	(	
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_INT_ATUAL		
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'comprometido'
							
			) COMPROMETIDO_TOTAL
		,	OCINV.hm_situacao SITUACAO
		,	OCINV.hm_fase FASE
		,   AREA_TI.NAME AREA_TI
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_CAPEX_ATUAL
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_OPEX_ATUAL

				,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_CAPEX_POST
			
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_OPEX_POST	
			
		, CLASSINV.NAME CLASS_GARTNER
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
			) PROJ_REC_INT_ATUAL
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
			) PROJ_REC_INT_FUT
	FROM
		NIKU.INV_INVESTMENTS INVI
		JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
		LEFT JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIR_EXEC ON DIR_EXEC.LOOKUP_CODE = OCINV.HM_NOME_DIRETORIA AND DIR_EXEC.LANGUAGE_CODE = 'pt' AND DIR_EXEC.LOOKUP_TYPE = 'HM_LKP_NOME_DIRETORIA' 
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIVISAO ON DIVISAO.LOOKUP_CODE = OCINV.HM_DIVISAO AND DIVISAO.LANGUAGE_CODE = 'pt' AND DIVISAO.LOOKUP_TYPE = 'HM_LKP_DIVISAO'
		LEFT JOIN NIKU.CMN_LOOKUPS_V HIERARQUIA_PRI ON HIERARQUIA_PRI.LOOKUP_CODE = INVI.GOAL_CODE AND HIERARQUIA_PRI.LANGUAGE_CODE = 'pt' AND HIERARQUIA_PRI.LOOKUP_TYPE = 'INVESTMENT_GOAL_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V AREA_TI ON AREA_TI.LOOKUP_CODE = OCINV.HM_AREA_TI AND AREA_TI.LANGUAGE_CODE = 'pt' AND AREA_TI.LOOKUP_TYPE = 'AREAS_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSIFICACAO ON CLASSIFICACAO.LOOKUP_CODE = OCPRJ.OBJ_REQUEST_TYPE AND CLASSIFICACAO.LANGUAGE_CODE = 'pt' AND CLASSIFICACAO.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.LOOKUP_CODE = PMPRJ.COST_TYPE  AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_PROJ ON TIPO_PROJ.LOOKUP_CODE = OCINV.hm_tipo_proj_ti  AND TIPO_PROJ.LANGUAGE_CODE = 'pt' AND TIPO_PROJ.LOOKUP_TYPE = 'HM_LKP_TIPO_PROJ_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSINV ON CLASSINV.LOOKUP_CODE = OCINV.hm_class_inv AND CLASSINV.LANGUAGE_CODE = 'pt' AND CLASSINV.LOOKUP_TYPE = 'HM_LKP_CLASS_INV'
	
	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'	
		AND OCPRJ.id_demanda_pai IS NULL
		AND INVI.NAME NOT LIKE '%COMPLEMENTAR%'
		AND OCINV.hm_class_inv IS NOT NULL
		
		
		
UNION

--PROJETOS FILHO
SELECT
		
		  INVI.CODE INV_CODE
		, INVI.ID INV_ID
		, INVI.ODF_OBJECT_CODE OBJ_CODE
		, INVI.NAME INV_NAME
		, DIR_EXEC.NAME DIR_EXEC
		, DIVISAO.NAME DIVISAO
		, HIERARQUIA_PRI.NAME HIER_PRI
		, TIPO_PROJ.NAME TIPO_PROJ
		, 'Priorizado ' + CONVERT(VARCHAR(4),OCINV.hm_ano_investimento,126) STATUS_PRI
		, (	
				SELECT 
					OCINV.hm_cust_ext
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON INVI.ID = PMP.ID
				WHERE 
					PMP.COST_TYPE = 'CAPITAL'
					AND OCINV.ID = INVI.IDEA_ID
				
			) GUESS_CAPEX
		, (	
				SELECT 
					OCINV.hm_cust_ext
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON INVI.ID = PMP.ID
				WHERE 
					PMP.COST_TYPE = 'OPERATING'
					AND OCINV.ID = INVI.IDEA_ID
					
			) GUESS_OPEX
		, (	
				SELECT 
					OCINV.hm_cust_int
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON OCINV.ID = PMP.ID
				WHERE 
					 OCINV.ID = INVI.IDEA_ID
			) GUESS_REC_INT
		, CLASSIFICACAO.NAME CLASSIFICACAO
		, OCPRJ.aprovacao_rep REP_APROVADA
		, OCINV.hm_cust_ext CUSTO_ESTIM_EXT
		, TIPO_CUSTO.NAME TIPO_CUSTO
		, 	(	
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') != 'RECINT')
			) ORC_CAPEX
			
		, 	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') != 'RECINT')
			) ORC_OPEX

		, (
			SELECT
				SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
			FROM
				NIKU.FIN_PLANS FIN_PLAN
				LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
				LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
				LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
				LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				
			WHERE
				FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
				AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
				AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
				AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') = 'RECINT')
			) ORC_REC_INT
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = OCPRJ_FILHO.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'CAPITAL'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_CAPEX_ANT
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = OCPRJ_FILHO.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'OPERATING'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_OPEX_ANT

		,	(	
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = OCPRJ_FILHO.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_INT_ANT
			
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = OCPRJ_FILHO.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'CAPITAL'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_CAPEX_ATUAL
			
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = OCPRJ_FILHO.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'OPERATING'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_OPEX_ATUAL
		
		,	(	
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = OCPRJ_FILHO.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_INT_ATUAL		
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'comprometido'
							
			) COMPROMETIDO_TOTAL
		,	OCINV.hm_situacao
		,	OCINV.hm_fase
		,   AREA_TI.NAME AREA_TI
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_CAPEX_ATUAL
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_OPEX_ATUAL

				,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_CAPEX_POST
			
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_OPEX_POST	
			
		, CLASSINV.NAME CLASS_GARTNER
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
			) PROJ_REC_INT_ATUAL
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = OCPRJ_FILHO.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
			) PROJ_REC_INT_FUT
	FROM
		NIKU.INV_INVESTMENTS INVI
		JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		JOIN NIKU.ODF_CA_PROJECT OCPRJ_FILHO ON INVI.CODE = OCPRJ_FILHO.id_demanda_pai
		LEFT JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
		LEFT JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIR_EXEC ON DIR_EXEC.LOOKUP_CODE = OCINV.HM_NOME_DIRETORIA AND DIR_EXEC.LANGUAGE_CODE = 'pt' AND DIR_EXEC.LOOKUP_TYPE = 'HM_LKP_NOME_DIRETORIA' 
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIVISAO ON DIVISAO.LOOKUP_CODE = OCINV.HM_DIVISAO AND DIVISAO.LANGUAGE_CODE = 'pt' AND DIVISAO.LOOKUP_TYPE = 'HM_LKP_DIVISAO'
		LEFT JOIN NIKU.CMN_LOOKUPS_V HIERARQUIA_PRI ON HIERARQUIA_PRI.LOOKUP_CODE = INVI.GOAL_CODE AND HIERARQUIA_PRI.LANGUAGE_CODE = 'pt' AND HIERARQUIA_PRI.LOOKUP_TYPE = 'INVESTMENT_GOAL_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V AREA_TI ON AREA_TI.LOOKUP_CODE = OCINV.HM_AREA_TI AND AREA_TI.LANGUAGE_CODE = 'pt' AND AREA_TI.LOOKUP_TYPE = 'AREAS_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSIFICACAO ON CLASSIFICACAO.LOOKUP_CODE = OCPRJ.OBJ_REQUEST_TYPE AND CLASSIFICACAO.LANGUAGE_CODE = 'pt' AND CLASSIFICACAO.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.LOOKUP_CODE = PMPRJ.COST_TYPE  AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_PROJ ON TIPO_PROJ.LOOKUP_CODE = OCINV.hm_tipo_proj_ti  AND TIPO_PROJ.LANGUAGE_CODE = 'pt' AND TIPO_PROJ.LOOKUP_TYPE = 'HM_LKP_TIPO_PROJ_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSINV ON CLASSINV.LOOKUP_CODE = OCINV.hm_class_inv AND CLASSINV.LANGUAGE_CODE = 'pt' AND CLASSINV.LOOKUP_TYPE = 'HM_LKP_CLASS_INV'
	
	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'	
		AND OCPRJ.id_demanda_pai IS NULL
		AND OCINV.hm_class_inv IS NOT NULL		
		
UNION

-- DEMANDAS
SELECT
		
		  INVI.CODE INV_CODE
		, INVI.ID INV_ID
		, INVI.ODF_OBJECT_CODE OBJ_CODE
		, INVI.NAME INV_NAME
		, DIR_EXEC.NAME DIR_EXEC
		, DIVISAO.NAME DIVISAO
		, HIERARQUIA_PRI.NAME HIER_PRI
		, TIPO_PROJ.NAME TIPO_PROJ
		, 'Priorizado ' + CONVERT(VARCHAR(4),OCINV.hm_ano_investimento,126) STATUS_PRI
		, (	
				SELECT 
					OCINV.hm_cust_ext
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON INVI.ID = PMP.ID
				WHERE 
					PMP.COST_TYPE = 'CAPITAL'
					AND OCINV.ID = INVI.IDEA_ID
				
			) GUESS_CAPEX
		, (	
				SELECT 
					OCINV.hm_cust_ext
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON INVI.ID = PMP.ID
				WHERE 
					PMP.COST_TYPE = 'OPERATING'
					AND OCINV.ID = INVI.IDEA_ID
					
			) GUESS_OPEX
		, (	
				SELECT 
					OCINV.hm_cust_int
				FROM 
					NIKU.ODF_CA_INV OCINV
					JOIN NIKU.PAC_MNT_PROJECTS PMP
					ON OCINV.ID = PMP.ID
				WHERE 
					 OCINV.ID = INVI.IDEA_ID
			) GUESS_REC_INT
		, CLASSIFICACAO.NAME CLASSIFICACAO
		, NULL REP_APROVADA
		, OCINV.hm_cust_ext CUSTO_ESTIM_EXT
		, TIPO_CUSTO.NAME TIPO_CUSTO
		, 	(	
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') != 'RECINT')
			) ORC_CAPEX
			
		, 	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') != 'RECINT')
			) ORC_OPEX

		, (
			SELECT
				SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
			FROM
				NIKU.FIN_PLANS FIN_PLAN
				LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
				LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
				LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
				LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				
			WHERE
				FIN_PLAN.OBJECT_ID = INVI.ID
				AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
				AND FIN_PLAN.PLAN_TYPE_CODE = 'BUDGET'
				AND (ISNULL(RES_CLASS.RESOURCE_CLASS,'') = 'RECINT')
			) ORC_REC_INT
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'CAPITAL'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_CAPEX_ANT
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'OPERATING'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_OPEX_ANT

		,	(	
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.TRANSDATE) < DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_INT_ANT
			
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'CAPITAL'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_CAPEX_ATUAL
			
		,	(
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS != 'RECINT'
					AND PW.COST_TYPE = 'OPERATING'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_OPEX_ATUAL
		
		,	(	
				SELECT	
					SUM(ISNULL(PV.TOTALCOST,0))
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.STATUS = 0
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.TRANSDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))		
			) GASTO_INT_ATUAL		
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'comprometido'
							
			) COMPROMETIDO_TOTAL
		,	OCINV.hm_situacao
		,	OCINV.hm_fase
		,   AREA_TI.NAME AREA_TI
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_CAPEX_ATUAL
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_OPEX_ATUAL

				,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'CAPITAL'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_CAPEX_POST
			
		,	(
				SELECT
					SUM(ISNULL((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.ID = FPD.COST_TYPE_ID AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE' 
					
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND TIPO_CUSTO.LOOKUP_CODE = 'OPERATING'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))			
			) PROJ_OPEX_POST	
			
		, CLASSINV.NAME CLASS_GARTNER
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
			) PROJ_REC_INT_ATUAL
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'projetado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,FP_COST.START_DATE) > DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
			) PROJ_REC_INT_FUT
	FROM
		NIKU.INV_INVESTMENTS INVI
		JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.ODF_CA_IDEA OCID ON INVI.ID = OCID.ID
		LEFT JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIR_EXEC ON DIR_EXEC.LOOKUP_CODE = OCINV.HM_NOME_DIRETORIA AND DIR_EXEC.LANGUAGE_CODE = 'pt' AND DIR_EXEC.LOOKUP_TYPE = 'HM_LKP_NOME_DIRETORIA' 
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIVISAO ON DIVISAO.LOOKUP_CODE = OCINV.HM_DIVISAO AND DIVISAO.LANGUAGE_CODE = 'pt' AND DIVISAO.LOOKUP_TYPE = 'HM_LKP_DIVISAO'
		LEFT JOIN NIKU.CMN_LOOKUPS_V HIERARQUIA_PRI ON HIERARQUIA_PRI.LOOKUP_CODE = INVI.GOAL_CODE AND HIERARQUIA_PRI.LANGUAGE_CODE = 'pt' AND HIERARQUIA_PRI.LOOKUP_TYPE = 'INVESTMENT_GOAL_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V AREA_TI ON AREA_TI.LOOKUP_CODE = OCINV.HM_AREA_TI AND AREA_TI.LANGUAGE_CODE = 'pt' AND AREA_TI.LOOKUP_TYPE = 'AREAS_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSIFICACAO ON CLASSIFICACAO.LOOKUP_CODE = OCID.OBJ_REQUEST_TYPE AND CLASSIFICACAO.LANGUAGE_CODE = 'pt' AND CLASSIFICACAO.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.LOOKUP_CODE = PMPRJ.COST_TYPE  AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_PROJ ON TIPO_PROJ.LOOKUP_CODE = OCINV.hm_tipo_proj_ti  AND TIPO_PROJ.LANGUAGE_CODE = 'pt' AND TIPO_PROJ.LOOKUP_TYPE = 'HM_LKP_TIPO_PROJ_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSINV ON CLASSINV.LOOKUP_CODE = OCINV.hm_class_inv AND CLASSINV.LANGUAGE_CODE = 'pt' AND CLASSINV.LOOKUP_TYPE = 'HM_LKP_CLASS_INV'
		LEFT JOIN NIKU.INV_INVESTMENTS INVP ON INVP.IDEA_ID = INVI.ID
	
	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'idea'	
		AND INVI.NAME NOT LIKE '%COMPLEMENTAR%'
		AND OCINV.hm_class_inv IS NOT NULL		
		AND OCINV.hm_situacao != 'hm_sit_convertida_projeto'
		AND INVP.ID IS NULL
) INVS

GROUP BY
INV_CODE
, INV_ID
, OBJ_CODE
, INV_NAME
, DIR_EXEC
, DIVISAO
, HIER_PRI
, TIPO_PROJ
, STATUS_PRI
, GUESS_CAPEX 
, GUESS_OPEX 
, GUESS_REC_INT 
, CUSTO_ESTIM_EXT
, CLASSIFICACAO
, REP_APROVADA
, CASE TIPO_CUSTO WHEN 'Operacional' THEN 'OPEX' ELSE 'CAPEX' END
, CASE  
WHEN FASE = 'hm_lkp_encerramento' AND SITUACAO = 'hm_sit_encerrado' THEN 'Encerrado'
WHEN FASE IN ('hm_lkp_spgl') THEN 'Entregue'
WHEN SITUACAO IN ('hm_sit_cancelada', 'hm_sit_cance_sol') THEN 'Cancelado'
WHEN SITUACAO IN ('hm_sit_on_hold', 'hm_sit_susp_solicitada') THEN 'On Hold'
WHEN OBJ_CODE = 'idea' OR FASE IN ('hm_aprovar_projeto', 'hm_analisar_projeto') THEN 'Em análise'
ELSE 'A entregar'
END 
, AREA_TI

) INVS_FINAL