SELECT
@SELECT:DIM:USER_DEF:IMPLIED:PRST:NIVEL.PRST_ID||NIVEL.RUBRICA_CODE:ID@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.REL_ID:REL_ID@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.PRST_NOME:PRST_NOME@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.PRST_ID:PRST_ID@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.RUBRICA:RUBRICA@,
@SELECT:METRIC:USER_DEF:IMPLIED:NIVEL.CUSTO:CUSTO@,
@SELECT:METRIC:USER_DEF:IMPLIED:NIVEL.REALIZADO:REALIZADO@,
@SELECT:METRIC:USER_DEF:IMPLIED:NIVEL.SALDO:SALDO@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.LINK:LINK@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.RUBRICA_MASTER:RUBRICA_MASTER@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.ENVIAR_AVALIACAO:ENVIAR_AVALIACAO@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.PRST_STATUS:PRST_STATUS@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PRST:NIVEL.HG_HAS_CHILDREN:HG_HAS_CHILDREN@
FROM
(SELECT TAB2.PRST_ID PRST_ID,
       NULL REL_ID,
       TAB2.PRST_NOME PRST_NOME,
       UPPER(TAB2.PRST_NOME)||' - '||TAB2.INICIO||' - '||TAB2.FIM RUBRICA,
       NULL RUBRICA_CODE,
       SUM(TAB2.CUSTO) CUSTO,
       SUM(TAB2.REALIZADO) REALIZADO,
       SUM(TAB2.SALDO) SALDO,
       NULL LINK,
       1 RUBRICA_MASTER,
	   'Clique aqui' ENVIAR_AVALIACAO,
	   TAB2.PRST_STATUS PRST_STATUS,
       (CASE WHEN (SELECT COUNT(*)
                   FROM ODF_CA_vale_rel_pag REL
                     LEFT JOIN odf_ca_vale_prestacao_conta prst ON REL.ODF_PARENT_ID = PRST.ID
                     LEFT JOIN CMN_LOOKUPS_V LOOK
                     ON PRST.VALE_NOME = LOOK.LOOKUP_CODE
                    AND LOOK.LOOKUP_TYPE = 'VALE_ETAPAS_PREST_CONTAS'
                    AND LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@
                   WHERE LOOK.NAME = TAB2.PRST_NOME) > 0 THEN (TAB2.PRST_NOME||TAB2.PRST_ID) ELSE NULL END) HG_HAS_CHILDREN
FROM (SELECT TAB.PRST_ID PRST_ID,
             NULL REL_ID,
             TAB.PRST_NOME PRST_NOME,
             TO_CHAR(TAB.INICIO,'dd/mm/yyyy') INICIO,
             TO_CHAR(TAB.FIM,'dd/mm/yyyy') FIM,
             TAB.RUBRICA RUBRICA,
             TAB.RUBRICA_CODE RUBRICA_CODE,
			 TAB.PRST_STATUS PRST_STATUS,
             SUM(TAB.CUSTO) CUSTO,
             SUM(TAB.REALIZADO) REALIZADO,
             SUM(TAB.SALDO) SALDO
      FROM (SELECT LOOK.NAME PRST_NOME,
                   PRST.ID PRST_ID,
                   PRST.VALE_INICIO INICIO,
                   PRST.VALE_FIM FIM,
                   (CASE WHEN HRUBRICAS.ditv_rubrica_master IS NULL THEN HRUBRICAS.NAME ELSE HRUBRICAS2.NAME END) RUBRICA,
                   (CASE WHEN HRUBRICAS.ditv_rubrica_master IS NULL THEN HRUBRICAS.CODE ELSE HRUBRICAS2.CODE END) RUBRICA_CODE,
                   NVL(REL.vale_csts,0) CUSTO,
                   NVL(rel.vale_val_tx,0) REALIZADO,
                   (NVL(REL.vale_csts,0) - NVL(rel.vale_val_tx,0)) SALDO,
				   look2.name PRST_STATUS,
                   NULL LINK
            FROM odf_ca_vale_prestacao_conta prst
              LEFT JOIN ODF_CA_vale_rel_pag REL ON REL.ODF_PARENT_ID = PRST.ID
              LEFT JOIN ODF_CA_VALE_HIERARQUIA_RUBR HRUBRICAS ON HRUBRICAS.CODE = REL.VALE_RUBRICA
              LEFT JOIN odf_ca_vale_hierarquia_rubr HRUBRICAS2 ON HRUBRICAS2.DITV_RUBRICA = HRUBRICAS.DITV_RUBRICA_MASTER
              LEFT JOIN CMN_LOOKUPS_V LOOK
                     ON PRST.VALE_NOME = LOOK.LOOKUP_CODE
                    AND LOOK.LOOKUP_TYPE = 'VALE_ETAPAS_PREST_CONTAS'
                    AND LOOK.LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@
              LEFT JOIN CMN_LOOKUPS_V LOOK2
                     ON PRST.VALE_STATUS = LOOK2.LOOKUP_CODE
                    AND LOOK2.LOOKUP_TYPE = 'VALE_STATUS_SOLICITACAO'
                    AND LOOK2.LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@
            WHERE prst.odf_parent_id = @where:param:xml:integer:/data/id/@value@) TAB
      WHERE @WHERE:PARAM:USER_DEF:string:hg_row_id@ IS NULL
      GROUP BY TAB.RUBRICA,
               TAB.PRST_NOME,
               TAB.RUBRICA_CODE,
			   TAB.PRST_STATUS,
               TAB.PRST_ID,
               TO_CHAR(TAB.INICIO,'dd/mm/yyyy'),
             TO_CHAR(TAB.FIM,'dd/mm/yyyy')) TAB2
WHERE TAB2.PRST_ID = @WHERE:PARAM:USER_DEF:INTEGER:PRST_ID@ OR @WHERE:PARAM:USER_DEF:INTEGER:PRST_ID@ IS NULL
GROUP BY TAB2.PRST_ID,
         TAB2.PRST_NOME,
		 UPPER(TAB2.PRST_NOME)||' - '||TAB2.INICIO||' - '||TAB2.FIM,
		 TAB2.PRST_STATUS
		 
UNION
SELECT TAB.PRST_ID PRST_ID,
NULL REL_ID,
TAB.PRST_NOME PRST_NOME,
       TAB.RUBRICA RUBRICA,
	   TAB.RUBRICA_CODE RUBRICA_CODE,
       SUM(TAB.CUSTO) CUSTO,
       SUM(TAB.REALIZADO) REALIZADO,
       SUM(TAB.SALDO) SALDO,
       NULL LINK,
	   1 RUBRICA_MASTER,
	   NULL ENVIAR_AVALIACAO,
	   NULL PRST_STATUS,
       (CASE WHEN (SELECT COUNT(*)
                   FROM ODF_CA_vale_rel_pag REL
                     LEFT JOIN odf_ca_vale_prestacao_conta prst ON REL.ODF_PARENT_ID = PRST.ID
                     LEFT JOIN ODF_CA_VALE_HIERARQUIA_RUBR HRUBRICAS ON HRUBRICAS.CODE = REL.VALE_RUBRICA
                     LEFT JOIN odf_ca_vale_hierarquia_rubr HRUBRICAS2 ON HRUBRICAS2.DITV_RUBRICA = HRUBRICAS.DITV_RUBRICA_MASTER
                   WHERE PRST.ID = TAB.PRST_ID
                   AND   (CASE WHEN HRUBRICAS2.NAME IS NULL THEN HRUBRICAS.name ELSE HRUBRICAS2.NAME END) = TAB.RUBRICA) > 0 THEN (TAB.RUBRICA||TAB.PRST_ID) ELSE NULL END) HG_HAS_CHILDREN
FROM (SELECT LOOK.NAME PRST_NOME,
             PRST.ID PRST_ID,
             (CASE WHEN HRUBRICAS.ditv_rubrica_master IS NULL THEN HRUBRICAS.NAME ELSE HRUBRICAS2.NAME END) RUBRICA,
			 (CASE WHEN HRUBRICAS.ditv_rubrica_master IS NULL THEN HRUBRICAS.CODE ELSE HRUBRICAS2.CODE END) RUBRICA_CODE,
             NVL(REL.vale_csts,0) CUSTO,
             NVL(rel.vale_val_tx,0) REALIZADO,
             (NVL(REL.vale_csts,0)-NVL(rel.vale_val_tx,0)) SALDO,
             NULL LINK
      FROM odf_ca_vale_prestacao_conta prst
        LEFT JOIN ODF_CA_vale_rel_pag REL ON REL.ODF_PARENT_ID = PRST.ID
        LEFT JOIN ODF_CA_VALE_HIERARQUIA_RUBR HRUBRICAS ON HRUBRICAS.CODE = REL.VALE_RUBRICA
        LEFT JOIN odf_ca_vale_hierarquia_rubr HRUBRICAS2 ON HRUBRICAS2.DITV_RUBRICA = HRUBRICAS.DITV_RUBRICA_MASTER
        LEFT JOIN CMN_LOOKUPS_V LOOK
               ON PRST.VALE_NOME = LOOK.LOOKUP_CODE
              AND LOOK.LOOKUP_TYPE = 'VALE_ETAPAS_PREST_CONTAS'
              AND LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@
      WHERE prst.odf_parent_id = @where:param:xml:integer:/data/id/@value@) TAB
WHERE TAB.PRST_NOME||TAB.PRST_ID = @WHERE:PARAM:USER_DEF:string:hg_row_id@ AND (TAB.PRST_ID = @WHERE:PARAM:USER_DEF:INTEGER:PRST_ID@ OR @WHERE:PARAM:USER_DEF:INTEGER:PRST_ID@ IS NULL)
GROUP BY TAB.RUBRICA,
         TAB.PRST_NOME,
	     TAB.RUBRICA_CODE,
         TAB.PRST_ID,
		 TAB.RUBRICA||TAB.PRST_ID
UNION
SELECT 
       PRST.ID PRST_ID,
	   REL.ID REL_ID,
	   PRST.NAME PRST_NOME,
       (CASE WHEN REL.VALE_ITEM IS NOT NULL THEN REL.VALE_ITEM ELSE HRUBRICAS.NAME END) RUBRICA,
	   HRUBRICAS.CODE||REL.ID RUBRICA_CODE,
       NVL(REL.vale_csts,0) CUSTO,
       NVL(rel.vale_val_tx,0) REALIZADO,
       (NVL(REL.vale_csts,0)-NVL(rel.vale_val_tx,0)) SALDO,
       'Clique aqui' LINK,
	   0 RUBRICA_MASTER,
	   NULL ENVIAR_AVALIACAO,
	   NULL PRST_STATUS,
       NULL HG_HAS_CHILDREN
FROM odf_ca_vale_prestacao_conta prst
  LEFT JOIN ODF_CA_vale_rel_pag REL ON REL.ODF_PARENT_ID = PRST.ID
  LEFT JOIN ODF_CA_VALE_HIERARQUIA_RUBR HRUBRICAS ON HRUBRICAS.CODE = REL.VALE_RUBRICA
  LEFT JOIN odf_ca_vale_hierarquia_rubr HRUBRICAS2 ON HRUBRICAS2.DITV_RUBRICA = HRUBRICAS.DITV_RUBRICA_MASTER
  LEFT JOIN CMN_LOOKUPS_V LOOK
         ON PRST.VALE_NOME = LOOK.LOOKUP_CODE
        AND LOOK.LOOKUP_TYPE = 'VALE_ETAPAS_PREST_CONTAS'
        AND LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@
WHERE prst.odf_parent_id = @where:param:xml:integer:/data/id/@value@ AND (PRST.ID = @WHERE:PARAM:USER_DEF:INTEGER:PRST_ID@ OR @WHERE:PARAM:USER_DEF:INTEGER:PRST_ID@ IS NULL)
and (CASE WHEN HRUBRICAS2.NAME IS NULL THEN HRUBRICAS.name ELSE HRUBRICAS2.NAME END)||PRST.ID = @where:param:user_def:string:hg_row_id@) NIVEL
WHERE 
	@FILTER@