SELECT  DISTINCT
	@SELECT:LOOKUP.LOOKUP_CODE:LOOKUP_CODE@,
	@SELECT:LOOKUP.NAME:LOOKUP_NAME@,
	@SELECT:LOOKUP.SORT_ORDER:LOOKUP_SORT@,
	@SELECT:MAP.LAST_UPDATED_DATE:LAST_UPDATED_DATE@,
	@SELECT:LANG.LANGUAGE_CODE:LANGUAGE_CODE@,
	@SELECT:LANG.ID:LANGUAGE_ID@
FROM    
	ODF_CA_COP_IDEA_PRJ_MAP MAP, 
	CMN_LOOKUPS_V LOOKUP, 
	CMN_LANGUAGES LANG
WHERE   
	MAP.CHILD_LOOKUP = LOOKUP.LOOKUP_CODE
	AND LOOKUP.LANGUAGE_CODE = LANG.LANGUAGE_CODE 
	AND LOOKUP.LOOKUP_TYPE = 'PR_TIPO_ALT_PROD_PROJ'
	AND LOOKUP.LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@
	AND (
			@WHERE:PARAM:USER_DEF:STRING:TYPE_CONSTRAIN@ IS NULL OR
			@WHERE:PARAM:USER_DEF:STRING:TYPE_CONSTRAIN@ = MAP.PARENT_LOOKUP
		)
	AND @FILTER@
	@BROWSE-ONLY: 
	AND LOOKUP.IS_ACTIVE=1 
	:BROWSE-ONLY@