SELECT
 PHASE.NAME PHASE
 ,COUNT(INVI.ID) QTD
, MAN.FIRST_NAME || ' ' || MAN.LAST_NAME  PROJECT_MANAGER
, BU.NAME BU
, PRJ_TYPE.NAME PROJECT_TYPE
, INVI.SCHEDULE_FINISH LAUNCH_DATE

FROM INV_INVESTMENTS INVI
JOIN ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
JOIN INV_PROJECTS INVP ON INVI.ID = INVP.PRID
JOIN CMN_LOOKUPS_V PHASE ON OCINV.san_proj_phase = PHASE.LOOKUP_CODE 
  AND PHASE.LOOKUP_TYPE='SAN_LKP_PROJ_PHASE' 
  AND PHASE.LANGUAGE_CODE = 'en'
LEFT JOIN SRM_RESOURCES MAN ON MAN.USER_ID = INVI.MANAGER_ID
LEFT JOIN CMN_LOOKUPS_V BU ON BU.LOOKUP_CODE = OCINV.SAN_BU 
  AND BU.LOOKUP_TYPE = 'SAN_LKP_BU' 
  AND BU.LANGUAGE_CODE = 'en'
LEFT JOIN CMN_LOOKUPS_V PRJ_TYPE ON PRJ_TYPE.LOOKUP_CODE = OCINV.SAN_PROJ_TYPE 
  AND PRJ_TYPE.LOOKUP_TYPE = 'SAN_LKP_PROJ_TYPE' 
  AND PRJ_TYPE.LANGUAGE_CODE = 'en'


WHERE INVI.IS_ACTIVE = 1
AND INVP.IS_TEMPLATE = 0

--INVI.MANAGER_ID = 
--AND INVI.SCHEDULE_FINISH >= 
--AND INVI.SCHEDULE_FINISH <= 
--AND OCINV.SAN_BU = 
--AND OCINV.san_proj_type =



GROUP BY PHASE.NAME
  , MAN.FIRST_NAME || ' ' || MAN.LAST_NAME
  , BU.NAME
  , PRJ_TYPE.NAME
  , INVI.SCHEDULE_FINISH

