SELECT
MAN.FIRST_NAME || ' ' || MAN.LAST_NAME  PROJECT_MANAGER
,COUNT(INVI.ID) QTD
, BU.NAME BU
, INVI.SCHEDULE_FINISH LAUNCH_DATE
, STAGE.NAME STAGE_GATE

FROM INV_INVESTMENTS INVI
JOIN ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
JOIN INV_PROJECTS INVP ON INVI.ID = INVP.PRID
LEFT JOIN CMN_LOOKUPS_V PHASE ON OCINV.san_proj_phase = PHASE.LOOKUP_CODE 
  AND PHASE.LOOKUP_TYPE='SAN_LKP_PROJ_PHASE' 
  AND PHASE.LANGUAGE_CODE = 'en'
LEFT JOIN SRM_RESOURCES MAN ON MAN.USER_ID = INVI.MANAGER_ID
LEFT JOIN CMN_LOOKUPS_V BU ON BU.LOOKUP_CODE = OCINV.SAN_BU 
  AND BU.LOOKUP_TYPE = 'SAN_LKP_BU' 
  AND BU.LANGUAGE_CODE = 'en'
LEFT JOIN CMN_LOOKUPS_V STAGE ON STAGE.LOOKUP_CODE = OCINV.SAN_STAGE_GATE
	AND STAGE.LOOKUP_TYPE = 'SAN_LKP_STAGE_GATE'
	AND STAGE.LANGUAGE_CODE = 'en'


WHERE INVI.IS_ACTIVE = 1
AND INVP.IS_TEMPLATE = 0

--AND OCINV.SAN_BU = 
--AND INVI.SCHEDULE_FINISH >= 
--AND INVI.SCHEDULE_FINISH <= 
-- AND OCINV.SAN_STAGE_GATE = 


GROUP BY PHASE.NAME
  , MAN.FIRST_NAME || ' ' || MAN.LAST_NAME
  , BU.NAME
  , INVI.SCHEDULE_FINISH
  , STAGE.NAME

