SELECT
PHASE
, COUNT(INV_ID) QTD
FROM
(
	SELECT
		 PHASE.NAME PHASE
		, INVI.ID INV_ID
		, MAN.FIRST_NAME || ' ' || MAN.LAST_NAME  PROJECT_MANAGER
		, BU.NAME BU
		, PRJ_TYPE.NAME PROJECT_TYPE
		, INVI.SCHEDULE_FINISH LAUNCH_DATE

	FROM 
		INV_INVESTMENTS INVI
		JOIN ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		JOIN INV_PROJECTS INVP ON INVI.ID = INVP.PRID
		JOIN CMN_LOOKUPS_V PHASE ON OCINV.san_proj_phase = PHASE.LOOKUP_CODE AND PHASE.LOOKUP_TYPE='SAN_LKP_PROJ_PHASE' AND PHASE.LANGUAGE_CODE = 'en'
		LEFT JOIN SRM_RESOURCES MAN ON MAN.USER_ID = INVI.MANAGER_ID
		LEFT JOIN CMN_LOOKUPS_V BU ON BU.LOOKUP_CODE = OCINV.SAN_BU AND BU.LOOKUP_TYPE = 'SAN_LKP_BU' AND BU.LANGUAGE_CODE = 'en'
		LEFT JOIN CMN_LOOKUPS_V PRJ_TYPE ON PRJ_TYPE.LOOKUP_CODE = OCINV.SAN_PROJ_TYPE AND PRJ_TYPE.LOOKUP_TYPE = 'SAN_LKP_PROJ_TYPE' AND PRJ_TYPE.LANGUAGE_CODE = 'en'

	WHERE 
		INVI.IS_ACTIVE = 1
		AND INVP.IS_TEMPLATE = 0
		AND INVI.SCHEDULE_FINISH BETWEEN TO_DATE($P{start_date},'dd/MM/yy') AND TO_DATE($P{finish_date},'dd/MM/yy')
)T1
WHERE
	$X{IN,BU,bu}
	AND $X{IN,PROJECT_TYPE,project_type}
	AND $X{IN,PROJECT_MANAGER,prj_manager}
	
GROUP BY
	PHASE

ORDER BY
	PHASE ASC