SELECT
	INV_ID
	, INV_CODE
	, INV_NAME
	, PROCESSO
	, INICIO_WF
	, INICIO_PLANEJAMENTO
	, FIM_PLANEJAMENTO
	, INICIO_EM_ATENDIMENTO
	, FIM_EM_ATENDIMENTO
	, INICIO_DEMANDA_ATEND
	, FIM_DEMANDA_ATEND
	, INICIO_DEF_SOLICITANTE
	, FIM_DEF_SOLICITANTE
	, TO_DATE(INICIO_WF, 'YYYY-MM-DD') - TO_DATE(FIM_PLANEJAMENTO, 'YYYY-MM-DD') INICIO_ATE_PLAN
	, TO_DATE(FIM_PLANEJAMENTO, 'YYYY-MM-DD') - TO_DATE(FIM_EM_ATENDIMENTO, 'YYYY-MM-DD') PLANEJ_ATE_EM_ATEND
	, TO_DATE(FIM_EM_ATENDIMENTO, 'YYYY-MM-DD') - TO_DATE(FIM_DEMANDA_ATEND, 'YYYY-MM-DD') EM_ATEND_ATE_DEM_ATEND
	, TO_DATE(FIM_PLANEJAMENTO, 'YYYY-MM-DD') - TO_DATE(FIM_DEMANDA_ATEND, 'YYYY-MM-DD') PLANEJ_ATE_DEM_ATEND
	, TO_DATE(INICIO_DEF_SOLICITANTE, 'YYYY-MM-DD') - TO_DATE(FIM_DEF_SOLICITANTE, 'YYYY-MM-DD') INICIO_TERMINO_DEF_SOLICITANTE
FROM
(
	SELECT
		AMTS3.INV_ID INV_ID
		, AMTS3.INV_CODE INV_CODE
		, AMTS3.INV_NAME INV_NAME
		, AMTS3.PROCESSO PROCESSO
		, AMTS3.INICIO_WF INICIO_WF
		, AMTS3.INICIO_PLANEJAMENTO INICIO_PLANEJAMENTO
		, AMTS3.FIM_PLANEJAMENTO FIM_PLANEJAMENTO
		, AMTS3.INICIO_EM_ATENDIMENTO INICIO_EM_ATENDIMENTO
		, AMTS3.FIM_EM_ATENDIMENTO FIM_EM_ATENDIMENTO
		, AMTS3.INICIO_DEMANDA_ATEND INICIO_DEMANDA_ATEND
		, AMTS3.FIM_DEMANDA_ATEND FIM_DEMANDA_ATEND
		, DEF_SOLICITANTE.INICIO_DEF_SOLICITANTE INICIO_DEF_SOLICITANTE
		, DEF_SOLICITANTE.FIM_DEF_SOLICITANTE FIM_DEF_SOLICITANTE
	FROM
	(
		SELECT
			AMTS2.INV_ID INV_ID
			, AMTS2.INV_CODE INV_CODE
			, AMTS2.INV_NAME INV_NAME
			, AMTS2.PROCESSO PROCESSO
			, AMTS2.INICIO_WF INICIO_WF
			, AMTS2.INICIO_PLANEJAMENTO INICIO_PLANEJAMENTO
			, AMTS2.FIM_PLANEJAMENTO FIM_PLANEJAMENTO
			, AMTS2.INICIO_EM_ATENDIMENTO INICIO_EM_ATENDIMENTO
			, AMTS2.FIM_EM_ATENDIMENTO FIM_EM_ATENDIMENTO
			, DEMANDA_ATEND.INICIO_DEMANDA_ATEND INICIO_DEMANDA_ATEND
			, DEMANDA_ATEND.FIM_DEMANDA_ATEND FIM_DEMANDA_ATEND
		FROM
		(
			SELECT
			  AMTS.INV_ID INV_ID
			  , AMTS.INV_CODE INV_CODE
			  , AMTS.INV_NAME INV_NAME
			  , AMTS.PROCESSO PROCESSO
			  , AMTS.INICIO_WF INICIO_WF
			  , AMTS.INICIO_PLANEJAMENTO INICIO_PLANEJAMENTO
			  , AMTS.FIM_PLANEJAMENTO FIM_PLANEJAMENTO
			  , EM_ATENDIMENTO.INICIO_EM_ATENDIMENTO INICIO_EM_ATENDIMENTO
			  , EM_ATENDIMENTO.FIM_EM_ATENDIMENTO FIM_EM_ATENDIMENTO
			FROM
			(
			  SELECT
			  T1.INV_ID
			  , T1.INV_CODE
			  , T1.INV_NAME
			  , T1.PROCESSO
			  , T1.INICIO_WF
			  , PLANEJAMENTO.INICIO_PLANEJAMENTO
			  , PLANEJAMENTO.FIM_PLANEJAMENTO
			  
			  FROM
			  (
				SELECT DISTINCT
				  INV.ID INV_ID
				  , INV.CODE INV_CODE
				  , INV.NAME INV_NAME
				  , CPRO.NAME PROCESSO
				  , RPRO.START_DATE INICIO_WF  
				FROM 
				  INV_INVESTMENTS INV 
				  JOIN BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
				  JOIN BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
				  JOIN BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
				  JOIN BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
				  JOIN CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
				WHERE
				  CPRO.NAME = 'TB - Gestão de Solicitação - DTT'
				  AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
				  AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
			  )T1
			  
			  LEFT JOIN
			  
			  (
				  SELECT DISTINCT
				  INV.ID INV_ID
				  , INV.CODE INV_CODE
				  , INV.NAME INV_NAME
				  , CPRO.NAME PROCESSO
				  , CSTP.NAME ETAPA
				  , RSTP.START_DATE INICIO_PLANEJAMENTO
				  , RSTP.END_DATE FIM_PLANEJAMENTO
				FROM 
				  INV_INVESTMENTS INV 
				  JOIN BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
				  JOIN BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
				  JOIN BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
				  JOIN BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
				  JOIN CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
				  JOIN BPM_RUN_STEPS RSTP ON RSTP.PROCESS_INSTANCE_ID = RPRO.ID
				  JOIN BPM_DEF_STEPS DSTP ON RSTP.STEP_ID = DSTP.ID
				  JOIN CMN_CAPTIONS_NLS CSTP ON DSTP.ID = CSTP.PK_ID AND CSTP.LANGUAGE_CODE = 'pt' AND CSTP.TABLE_NAME = 'BPM_DEF_STEPS'
				  JOIN BPM_RUN_STEP_ACTION_RESULTS SAR ON SAR.STEP_INSTANCE_ID = RSTP.ID 
				  JOIN BPM_DEF_STEP_ACTIONS DACT ON DACT.ID = SAR.STEP_ACTION_ID
			   WHERE
				  CPRO.NAME = 'TB - Gestão de Solicitação - DTT'
				  AND ( CSTP.NAME = 'Planejamento D' || '&' ||'S/SN' OR CSTP.NAME = 'Planejamento D' || '&' ||'S/Trans')
				  AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
				  AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
			  )PLANEJAMENTO
			  
			  ON T1.INV_ID = PLANEJAMENTO.INV_ID AND T1.PROCESSO = PLANEJAMENTO.PROCESSO
			  
			  WHERE
				T1.INV_CODE = 'TB00010636'
			)AMTS

			LEFT JOIN

			(
			  SELECT DISTINCT
				  INV.ID INV_ID
				  , INV.CODE INV_CODE
				  , INV.NAME INV_NAME
				  , CPRO.NAME PROCESSO
				  , CSTP.NAME ETAPA
				  , RSTP.START_DATE INICIO_EM_ATENDIMENTO
				  , RSTP.END_DATE FIM_EM_ATENDIMENTO
				FROM 
				  INV_INVESTMENTS INV 
				  JOIN BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
				  JOIN BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
				  JOIN BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
				  JOIN BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
				  JOIN CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
				  JOIN BPM_RUN_STEPS RSTP ON RSTP.PROCESS_INSTANCE_ID = RPRO.ID
				  JOIN BPM_DEF_STEPS DSTP ON RSTP.STEP_ID = DSTP.ID
				  JOIN CMN_CAPTIONS_NLS CSTP ON DSTP.ID = CSTP.PK_ID AND CSTP.LANGUAGE_CODE = 'pt' AND CSTP.TABLE_NAME = 'BPM_DEF_STEPS'
				  JOIN BPM_RUN_STEP_ACTION_RESULTS SAR ON SAR.STEP_INSTANCE_ID = RSTP.ID 
				  JOIN BPM_DEF_STEP_ACTIONS DACT ON DACT.ID = SAR.STEP_ACTION_ID
			   WHERE
				  CPRO.NAME = 'TB - Gestão de Solicitação - DTT'
				  AND CSTP.NAME = 'Em Atendimento'
				  AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
				  AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
			)EM_ATENDIMENTO

			ON AMTS.INV_ID = EM_ATENDIMENTO.INV_ID AND AMTS.PROCESSO = EM_ATENDIMENTO.PROCESSO
			  
			  WHERE
				AMTS.INV_CODE = 'TB00010636'
		)AMTS2

		LEFT JOIN

		(
			SELECT DISTINCT
				INV.ID INV_ID
				, INV.CODE INV_CODE
				, INV.NAME INV_NAME
				, CPRO.NAME PROCESSO
				, CSTP.NAME ETAPA
				, RSTP.START_DATE INICIO_DEMANDA_ATEND
				, RSTP.END_DATE FIM_DEMANDA_ATEND
			  FROM 
				INV_INVESTMENTS INV 
				JOIN BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
				JOIN BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
				JOIN BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
				JOIN BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
				JOIN CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
				JOIN BPM_RUN_STEPS RSTP ON RSTP.PROCESS_INSTANCE_ID = RPRO.ID
				JOIN BPM_DEF_STEPS DSTP ON RSTP.STEP_ID = DSTP.ID
				JOIN CMN_CAPTIONS_NLS CSTP ON DSTP.ID = CSTP.PK_ID AND CSTP.LANGUAGE_CODE = 'pt' AND CSTP.TABLE_NAME = 'BPM_DEF_STEPS'
				JOIN BPM_RUN_STEP_ACTION_RESULTS SAR ON SAR.STEP_INSTANCE_ID = RSTP.ID 
				JOIN BPM_DEF_STEP_ACTIONS DACT ON DACT.ID = SAR.STEP_ACTION_ID
			 WHERE
				CPRO.NAME = 'TB - Gestão de Solicitação - DTT'
				AND CSTP.NAME = 'Demanda Atendida'
				AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
				AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
		)DEMANDA_ATEND

		ON AMTS2.INV_ID = DEMANDA_ATEND.INV_ID AND AMTS2.PROCESSO = DEMANDA_ATEND.PROCESSO
		
	)AMTS3

	LEFT JOIN

	(
		SELECT DISTINCT
			INV.ID INV_ID
			, INV.CODE INV_CODE
			, INV.NAME INV_NAME
			, CPRO.NAME PROCESSO
			, CSTP.NAME ETAPA
			, RSTP.START_DATE INICIO_DEF_SOLICITANTE
			, RSTP.END_DATE FIM_DEF_SOLICITANTE
		  FROM 
			INV_INVESTMENTS INV 
			JOIN BPM_RUN_OBJECTS ROBJ ON ROBJ.OBJECT_ID = INV.ID --AND ROBJ.OBJECT_TYPE_CODE='PROJECT'
			JOIN BPM_RUN_PROCESSES RPRO ON RPRO.ID = ROBJ.PK_ID AND ROBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
			JOIN BPM_DEF_PROCESS_VERSIONS DPROV ON DPROV.ID = RPRO.PROCESS_VERSION_ID
			JOIN BPM_DEF_PROCESSES DPRO ON DPROV.PROCESS_ID = DPRO.ID
			JOIN CMN_CAPTIONS_NLS CPRO ON DPRO.ID = CPRO.PK_ID AND CPRO.LANGUAGE_CODE = 'pt' AND CPRO.TABLE_NAME = 'BPM_DEF_PROCESSES'
			JOIN BPM_RUN_STEPS RSTP ON RSTP.PROCESS_INSTANCE_ID = RPRO.ID
			JOIN BPM_DEF_STEPS DSTP ON RSTP.STEP_ID = DSTP.ID
			JOIN CMN_CAPTIONS_NLS CSTP ON DSTP.ID = CSTP.PK_ID AND CSTP.LANGUAGE_CODE = 'pt' AND CSTP.TABLE_NAME = 'BPM_DEF_STEPS'
			JOIN BPM_RUN_STEP_ACTION_RESULTS SAR ON SAR.STEP_INSTANCE_ID = RSTP.ID 
			JOIN BPM_DEF_STEP_ACTIONS DACT ON DACT.ID = SAR.STEP_ACTION_ID
		 WHERE
			CPRO.NAME = 'TB - Gestão de Solicitação - DTT'
			AND CSTP.NAME = 'Em Definição pelo Solicitante'
			AND RPRO.STATUS_CODE NOT LIKE '%ERROR%'
			AND RPRO.STATUS_CODE NOT LIKE '%ABORT%'
	)DEF_SOLICITANTE

	ON AMTS3.INV_ID = DEF_SOLICITANTE.INV_ID AND AMTS3.PROCESSO = DEF_SOLICITANTE.PROCESSO
)FINAL