SELECT
	
	SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0)) VALOR

FROM
	NIKU.FIN_PLANS FIN_PLAN
	LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
	LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
	
WHERE
	FIN_PLAN.OBJECT_ID = 5244003
	AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
	AND FP_COST.START_DATE >= CONVERT(VARCHAR(4),DATEPART(YEAR,GETDATE()) + 1) +'-01-01'