------------------------------------ REALIZADO ANO ANTERIOR ------------------------------------ 

SELECT
	Categoria
	, "Classificação"
	, SUM(Valor) Valor

FROM
(
	SELECT
		('Realizado ' + CONVERT(Varchar(4),DATEPART(YEAR,GETDATE())-1)) Categoria
		, CLA_PROJ.NAME "Classificação"
		,	(
				SELECT 
					ISNULL(SUM(PV.TOTALCOST),0)
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					LEFT JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = PW.INVESTMENT_ID
					LEFT JOIN NIKU.INV_INVESTMENTS INV ON PW.INVESTMENT_ID = INV.ID
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1)) - 1			
			) Valor				

	FROM
		NIKU.INV_INVESTMENTS INVI
		LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLA_PROJ ON CLA_PROJ.LOOKUP_CODE = OCINV.HM_CLASS_INV AND CLA_PROJ.LANGUAGE_CODE = 'pt' AND CLA_PROJ.LOOKUP_TYPE = 'HM_LKP_CLASS_INV' 

	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'
		AND CLA_PROJ.NAME IS NOT NULL

)AMTS

GROUP BY
Categoria
, "Classificação"

UNION ALL

SELECT
	Categoria
	, "Classificação"
	, SUM(Valor) Valor
FROM
(
	SELECT
		('Realizado ' + CONVERT(Varchar(4),DATEPART(YEAR,GETDATE())-1)) Categoria
		, 'Operação' "Classificação"
		,	(
				SELECT 
					ISNULL(SUM(PV.TOTALCOST),0)
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS	
				WHERE 
					DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1)) - 1			
			) Valor				

	FROM
		NIKU.INV_INVESTMENTS INVI
		LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		
	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'
)AMTS

GROUP BY
Categoria
, "Classificação"

------------------------------------ REALIZADO MÊS/ANO ATUAL ------------------------------------ 

UNION ALL

SELECT
	Categoria
	, "Classificação"
	, SUM(Valor) Valor

FROM
(
	SELECT
		('Realizado ' + CONVERT(VARCHAR(7),(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1),120)) Categoria
		, CLA_PROJ.NAME "Classificação"
		,	(
				SELECT 
					ISNULL(SUM(PV.TOTALCOST),0)
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					LEFT JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = PW.INVESTMENT_ID
					LEFT JOIN NIKU.INV_INVESTMENTS INV ON PW.INVESTMENT_ID = INV.ID
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND INV.ODF_OBJECT_CODE = 'project'
					AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
					AND PW.ENTRYDATE <= (SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1)
							
			) Valor				

	FROM
		NIKU.INV_INVESTMENTS INVI
		LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLA_PROJ ON CLA_PROJ.LOOKUP_CODE = OCINV.HM_CLASS_INV AND CLA_PROJ.LANGUAGE_CODE = 'pt' AND CLA_PROJ.LOOKUP_TYPE = 'HM_LKP_CLASS_INV' 

	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'
		AND CLA_PROJ.NAME IS NOT NULL

)AMTS

GROUP BY
Categoria
, "Classificação"

UNION ALL

SELECT
	Categoria
	, "Classificação"
	, SUM(Valor) Valor
FROM
(
	SELECT
		('Realizado ' + CONVERT(VARCHAR(7),(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1),120)) Categoria
		, 'Operação' "Classificação"
		,	(
				SELECT 
					ISNULL(SUM(PV.TOTALCOST),0)
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
					
				WHERE 
					INVI.ODF_OBJECT_CODE = 'project'
					AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,(SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1))
					AND PW.ENTRYDATE <= (SELECT MAX(hm_data_corte) FROM NIKU.ODF_CA_HM_DATA_RELATORIO WHERE hm_aprovado = 1)			
			) Valor				

	FROM
		NIKU.INV_INVESTMENTS INVI
		LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		
	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'
)AMTS

GROUP BY
Categoria
, "Classificação"

------------------------------------ PLANEJADO/ORÇADO ANO ATUAL ------------------------------------ 

UNION ALL

SELECT
	Categoria
	, "Classificação"
	, SUM(Valor) Valor

FROM
(
	SELECT
		('Orçamento ' + CONVERT(Varchar(4),DATEPART(YEAR,GETDATE()))) Categoria
		, CLA_PROJ.NAME "Classificação"
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V COST_TYPE ON COST_TYPE.ID = FPD.COST_TYPE_ID  AND COST_TYPE.LANGUAGE_CODE = 'pt' AND COST_TYPE.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'	
					--AND INV.ODF_OBJECT_CODE = 'project'
			) Valor			

	FROM
		NIKU.INV_INVESTMENTS INVI
		LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLA_PROJ ON CLA_PROJ.LOOKUP_CODE = OCINV.HM_CLASS_INV AND CLA_PROJ.LANGUAGE_CODE = 'pt' AND CLA_PROJ.LOOKUP_TYPE = 'HM_LKP_CLASS_INV' 

	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'
		AND CLA_PROJ.NAME IS NOT NULL

)AMTS

GROUP BY
Categoria
, "Classificação"

UNION ALL

SELECT
	Categoria
	, "Classificação"
	, SUM(Valor) Valor

FROM
(
	SELECT
		('Orçamento ' + CONVERT(Varchar(4),DATEPART(YEAR,GETDATE()))) Categoria
		, 'Operação' "Classificação"
		, 	(
				SELECT 
					SUM(ISNULL(ROUND((DATEDIFF(DAY, FP_COST.START_DATE, FP_COST.FINISH_DATE) * FP_COST.SLICE), 0), 0))
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
					JOIN NIKU.FIN_PLANS FIN_PLAN ON FIN_PLAN.OBJECT_ID = INVI.ID
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD ON FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST ON FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					JOIN NIKU.TRANSCLASS TC ON TC.ID = FPD.TRANSACTION_CLASS_ID
					JOIN NIKU.PAC_FOS_RESOURCE_CLASS RC ON RC.ID = FPD.RESOURCE_CLASS_ID
				WHERE 
					INVI.ODF_OBJECT_CODE = 'project'
					AND OCA_COST.hm_tipo_plano_custo = 'planejado'
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
			) Valor			

	FROM
		NIKU.INV_INVESTMENTS INVI
		LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLA_PROJ ON CLA_PROJ.LOOKUP_CODE = OCINV.HM_CLASS_INV AND CLA_PROJ.LANGUAGE_CODE = 'pt' AND CLA_PROJ.LOOKUP_TYPE = 'HM_LKP_CLASS_INV' 

	WHERE
		INVI.IS_ACTIVE = 1
		AND INVI.ODF_OBJECT_CODE = 'project'
		AND CLA_PROJ.NAME IS NOT NULL

)AMTS

GROUP BY
Categoria
, "Classificação"