SELECT
*
, CASE
	WHEN DATEPART(YEAR,"Data") = DATEPART(YEAR,GETDATE()) - 1 THEN 'Ano Anterior'
	WHEN DATEPART(YEAR,"Data") = DATEPART(YEAR,GETDATE()) THEN 'Ano Atual'
	WHEN DATEPART(YEAR,"Data") = DATEPART(YEAR,GETDATE()) + 1 THEN 'Ano Posterior'
	ELSE 'Não Informado'
	END "Data de Referência - Status"
FROM
(
	SELECT
	"ÍD do Projeto"
	, "Descrição do Projetos"
	, "Status"
	, CASE
		WHEN "Status" = 'A entregar' THEN "Data Go Live"
		WHEN "Status" = 'Entregue' THEN "Data Go Live"
		WHEN "Status" = 'Cancelado' THEN "Data Cancelamento/Suspensão"
		WHEN "Status" = 'On Hold' THEN "Data Cancelamento/Suspensão"
		END "Data"
	, ISNULL(SUM("Aprov REP"),0) "Aprovado REP"
	, ISNULL(SUM("Aprov REP Capex"),0) "Aprovado REP Capex"
	, ISNULL(SUM("Aprov REP Opex"),0) "Aprovado REP Opex"
	--, ISNULL(SUM("Aprov Recursos Internos"),0) "Aprov Recursos Internos"
	, ISNULL(SUM("Anos Ant Capex" ),0) "Anos Anteriores Realizado Capex" 
	, ISNULL(SUM("Anos Ant Opex"),0) "Anos Anteriores Realizado Opex"
	--, ISNULL(SUM("Anos Ant Recursos Internos"),0) "Anos Ant Recursos Internos"
	, ISNULL(SUM("Ano atual Gasto Capex"),0) "Ano atual Realizado Capex"
	, ISNULL(SUM("Ano atual Gasto Opex"),0) "Ano atual Realizado Opex"
	--, ISNULL(SUM("Anos atual Recursos Internos"),0) "Anos atual Recursos Internos"
	, ISNULL(SUM("Ano atual Prev Capex"),0) "Ano atual Planejado Capex"
	, ISNULL(SUM("Ano Atual Prev Opex"),0) "Ano Atual Planejado Opex"
	--, ISNULL(SUM("Ano Atual Prev Recursos Internos"),0) "Ano Atual Prev Recursos Internos"
	, ISNULL(SUM("Anos Post Prev Capex"),0) "Anos Posteriores Planejado de Capex"
	, ISNULL(SUM("Anos Post Prev Opex"),0) "Anos Posteriores Planejado de Opex"
	--, ISNULL(SUM("Anos Post Prev Recursos Internos"),0) "Anos Post Prev Recursos Internos"
	, ISNULL(SUM("Realizado Capex"),0) "Total Realizado de Capex"
	, ISNULL(SUM("Realizado Opex"),0) "Total Realizado de Opex"
	, ISNULL(SUM("Realizado Capex" + "Realizado Opex"),0) "Total Realizado"


	FROM
	(
		SELECT
			INVI.NAME "Descrição do Projetos"
			, INVI.CODE "Código do Projeto"
			, INVI.ID "ÍD do Projeto"
			, TIPO_PROJ.NAME "Tipo do projeto"
			, CASE 
				WHEN OCPRJ.data_go_live IS NOT NULL THEN OCPRJ.data_go_live
				WHEN OCPRJ.data_go_live IS NULL THEN OCPRJ.hm_data_go_live_orig
				WHEN OCPRJ.data_go_live IS NULL AND OCPRJ.hm_data_go_live_orig IS NULL THEN NULL
				ELSE NULL
				END "Data Go Live"
			, OCPRJ.data_cancelamento "Data Cancelamento/Suspensão"
			, CASE 
				WHEN STATUS.NAME = 'Desenho' THEN 'A entregar'
				WHEN STATUS.NAME = 'Desenvolvimento' THEN 'A entregar'
				WHEN STATUS.NAME = 'Planejamento' THEN 'A entregar'
				WHEN STATUS.NAME = 'Preparação Final' THEN 'A entregar'
				WHEN STATUS.NAME = 'Testes' THEN 'A entregar'
				WHEN STATUS.NAME = 'Cancelada' THEN 'Cancelado'
				WHEN STATUS.NAME = 'Cancelamento Solicitado' THEN 'Cancelado'
				WHEN STATUS.NAME = 'Aguardando Aprovação' THEN 'Em análise'
				WHEN STATUS.NAME = 'Aprovada' THEN 'Em análise'
				WHEN STATUS.NAME = 'Convertida em Projeto' THEN 'Em análise'
				WHEN STATUS.NAME = 'Em Análise' THEN 'Em análise'
				WHEN STATUS.NAME = 'Em Análise da Viab. Técnica' THEN 'Em análise'
				WHEN STATUS.NAME = 'Em Análise Para Aprovação' THEN 'Em análise'
				WHEN STATUS.NAME = 'Não Existe' THEN 'Em análise'
				WHEN STATUS.NAME = 'Planejando Solução' THEN 'Em análise'
				WHEN STATUS.NAME = 'Priorizada' THEN 'Em análise'
				WHEN STATUS.NAME = 'Solicitada' THEN 'Em análise'
				WHEN STATUS.NAME = 'Validando Planejamento' THEN 'Em análise'
				WHEN STATUS.NAME = 'Encerrado' THEN 'Entregue'
				WHEN STATUS.NAME = 'Encerramento' THEN 'Entregue'
				WHEN STATUS.NAME = 'SPGL' THEN 'Entregue'
				WHEN STATUS.NAME = 'On Hold' THEN 'On Hold'
				WHEN STATUS.NAME = 'Suspensão Solicitada' THEN 'On Hold'				
				END STATUS
			, DIR_EXEC.NAME "Diretoria Executiva"
			, CASE
				WHEN CUSTO_DEMANDA.NAME = 'Maior que 250K' THEN '>= 250K'
				WHEN CUSTO_DEMANDA.NAME = 'Maior que 500K' THEN '>= 250K'
				WHEN CUSTO_DEMANDA.NAME = 'Entre 150K e 500K' THEN '>= 250K'
				ELSE '< 250K'
				END "> 500K ?"
			, ISNULL(FFIN.PLANNED_CST_TOTAL,0) "Aprov REP"
			, ISNULL(FFIN.PLANNED_CST_CAPITAL_TOTAL,0) "Aprov REP Capex"
			, ISNULL(FFIN.PLANNED_CST_OPERATING_TOTAL,0) "Aprov REP Opex"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
						LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND RES_CLASS.RESOURCE_CLASS = 'RECINT'				
				) "Aprov Recursos Internos"
			, 	(
					SELECT 
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.COST_TYPE = 'CAPITAL'
						AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE()) - 1			
				) "Anos Ant Capex"
			, 	(
					SELECT 
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.COST_TYPE = 'OPERATING'
						AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE()) - 1			
				) "Anos Ant Opex"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
						LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE()) - 1		
				) "Anos Ant Recursos Internos"
			,	(
					SELECT 
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.COST_TYPE = 'CAPITAL'
						AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE())
				) "Ano atual Gasto Capex"
			,	(
					SELECT 
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.COST_TYPE = 'OPERATING'
						AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE())
				) "Ano atual Gasto Opex"
			,	(
					SELECT	
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.RESOURCE_CLASS = 'RECINT'
						AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE())		
				) "Anos atual Recursos Internos"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V COST_TYPE ON COST_TYPE.ID = FPD.COST_TYPE_ID  AND COST_TYPE.LANGUAGE_CODE = 'pt' AND COST_TYPE.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND COST_TYPE.NAME = 'CAPEX'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE())		
				) "Ano atual Prev Capex"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V COST_TYPE ON COST_TYPE.ID = FPD.COST_TYPE_ID  AND COST_TYPE.LANGUAGE_CODE = 'pt' AND COST_TYPE.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND COST_TYPE.NAME = 'OPEX'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE())		
				) "Ano Atual Prev Opex"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
						LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE())	
				) "Ano Atual Prev Recursos Internos"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V COST_TYPE ON COST_TYPE.ID = FPD.COST_TYPE_ID  AND COST_TYPE.LANGUAGE_CODE = 'pt' AND COST_TYPE.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND COST_TYPE.NAME = 'CAPEX'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE()) + 1	
				) "Anos Post Prev Capex"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V COST_TYPE ON COST_TYPE.ID = FPD.COST_TYPE_ID  AND COST_TYPE.LANGUAGE_CODE = 'pt' AND COST_TYPE.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND COST_TYPE.NAME = 'OPEX'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE()) + 1		
				) "Anos Post Prev Opex"
			, 	(
					SELECT
						SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
					FROM
						NIKU.FIN_PLANS FIN_PLAN
						LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
						LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
						LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
						LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
						LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
					WHERE
						FIN_PLAN.OBJECT_ID = INVI.ID
						AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
						AND hm_tipo_plano_custo = 'planejado'
						AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
						AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE()) + 1
				) "Anos Post Prev Recursos Internos"
			,	(
					SELECT 
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.COST_TYPE = 'CAPITAL'
				) "Realizado Capex"
			,	(
					SELECT 
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.COST_TYPE = 'OPERATING'
				) "Realizado Opex"
			,	(
					SELECT	
						ISNULL(SUM(PV.TOTALCOST),0)
					FROM 
						NIKU.PPA_WIP PW 
						LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
					WHERE
						PW.INVESTMENT_ID = INVI.ID
						AND PW.RESOURCE_CLASS = 'RECINT'
				) "Realizado Recursos Internos"
			

		FROM
			NIKU.INV_INVESTMENTS INVI
			LEFT JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
			LEFT JOIN NIKU.ODF_CA_INV IDEA_OCINV ON INVI.IDEA_ID = IDEA_OCINV.ID
			LEFT JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
			LEFT JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
			LEFT JOIN NIKU.FIN_FINANCIALS FFIN ON INVI.ID = FFIN.ID
			LEFT JOIN NIKU.FIN_FINANCIALS IDEA_FFIN ON IDEA_FFIN.ID = INVI.IDEA_ID
			LEFT JOIN NIKU.FIN_PLANS FIN_PLAN ON FIN_PLAN.OBJECT_ID = INVI.ID AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
			LEFT JOIN NIKU.BIZ_COM_PERIODS BIZ ON BIZ.ID = FIN_PLAN.END_PERIOD_ID
			LEFT JOIN NIKU.CMN_SEC_USERS USR ON USR.ID = INVI.MANAGER_ID
			LEFT JOIN NIKU.ODF_CA_HM_ORDEM_SAP OSAP ON OSAP.ODF_PARENT_ID = INVI.ID
			LEFT JOIN NIKU.CMN_LOOKUPS_V DIR_EXEC ON DIR_EXEC.LOOKUP_CODE = OCINV.HM_NOME_DIRETORIA AND DIR_EXEC.LANGUAGE_CODE = 'pt' AND DIR_EXEC.LOOKUP_TYPE = 'HM_LKP_NOME_DIRETORIA' 
			LEFT JOIN NIKU.CMN_LOOKUPS_V DIVISAO ON DIVISAO.LOOKUP_CODE = OCINV.HM_DIVISAO AND DIVISAO.LANGUAGE_CODE = 'pt' AND DIVISAO.LOOKUP_TYPE = 'HM_LKP_DIVISAO'
			LEFT JOIN NIKU.CMN_LOOKUPS_V HIERARQUIA_PRI ON HIERARQUIA_PRI.LOOKUP_CODE = INVI.GOAL_CODE AND HIERARQUIA_PRI.LANGUAGE_CODE = 'pt' AND HIERARQUIA_PRI.LOOKUP_TYPE = 'INVESTMENT_GOAL_TYPE'
			LEFT JOIN NIKU.CMN_LOOKUPS_V AREA_TI ON AREA_TI.LOOKUP_CODE = OCINV.HM_AREA_TI AND AREA_TI.LANGUAGE_CODE = 'pt' AND AREA_TI.LOOKUP_TYPE = 'AREAS_TI'
			LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSIFICACAO ON CLASSIFICACAO.LOOKUP_CODE = OCPRJ.OBJ_REQUEST_TYPE AND CLASSIFICACAO.LANGUAGE_CODE = 'pt' AND CLASSIFICACAO.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE'
			LEFT JOIN NIKU.CMN_LOOKUPS_V CUSTO_DEMANDA ON CUSTO_DEMANDA.LOOKUP_CODE = OCPRJ.CUSTO_DEMANDA AND CUSTO_DEMANDA.LANGUAGE_CODE = 'pt' AND CUSTO_DEMANDA.LOOKUP_TYPE = 'CUSTO_DEMANDA'
			LEFT JOIN NIKU.CMN_LOOKUPS_V STATUS ON STATUS.LOOKUP_CODE = OCINV.HM_SITUACAO AND STATUS.LANGUAGE_CODE = 'pt' AND STATUS.LOOKUP_TYPE = 'HM_SITUACAO'
			LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.LOOKUP_CODE = PMPRJ.COST_TYPE  AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
			LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_PROJ ON TIPO_PROJ.LOOKUP_CODE = OCPRJ.obj_request_type AND TIPO_PROJ.LANGUAGE_CODE = 'pt' AND TIPO_PROJ.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE'
			
		WHERE
			INVI.IS_ACTIVE = 1
			AND INVI.ODF_OBJECT_CODE = 'project'
			--AND INVI.ID = 5286001
	)DETAIL_PROJ
		
	GROUP BY
		"ÍD do Projeto"
		, "Descrição do Projetos"
		, "Data Cancelamento/Suspensão"
		, "Data Go Live"
		, "Status"
) AMTS
ORDER BY
	"Aprovado REP" DESC