SELECT
*
FROM
(

	SELECT
		RECURSO
		, FULL_NAME
		, DATA
		, HORA_INICIO
		, HORA_FIM
		, HORAS_AUSENTES
		, MINUTOS
		, SALDO_HORAS
		, TOTAL
	FROM
	(
		SELECT
			RES.ID RECURSO
			, RES.FIRST_NAME + ' ' + RES.LAST_NAME FULL_NAME
			, hm_dia DATA
			, ISNULL(hm_hora_inicio,'00:00') HORA_INICIO
			, ISNULL(hm_hora_fim,'00:00') HORA_FIM
			, hm_horas_ausentes HORAS_AUSENTES
			, ISNULL(DATEDIFF(MINUTE, hm_hora_inicio, hm_hora_fim),0) MINUTOS
			, CONVERT(VARCHAR(5),CONVERT(TIME(0), DATEADD(MINUTE, 60*ISNULL(hm_total_horas_qtd,0), 0))) SALDO_HORAS
			, '' TOTAL
			
		FROM
			NIKU.ODF_CA_HM_REGISTRO_PONTO REG
			LEFT JOIN NIKU.SRM_RESOURCES RES ON RES.USER_ID = REG.hm_recurso

		--WHERE
		--	REG.hm_recurso = 5003032
	) REG_PONTO

		UNION ALL

		SELECT
			NULL RECURSO
			, NULL FULL_NAME
			, NULL DATA
			, NULL HORA_INICIO
			, NULL HORA_FIM
			, NULL HORAS_AUSENTES
			, NULL MINUTOS
			, NULL SALDO_HORAS
			, CONVERT(VARCHAR(4),FLOOR(SUM(ISNULL(hm_total_horas_qtd,0)))) + ':' +  RIGHT('00'+CONVERT(VARCHAR(2),(FLOOR(SUM(ISNULL(hm_total_horas_qtd,0)) * 60) %60)),2) TOTAL

			
		FROM
			NIKU.ODF_CA_HM_REGISTRO_PONTO REG
			LEFT JOIN NIKU.SRM_RESOURCES RES ON RES.USER_ID = REG.hm_recurso

		--WHERE
		--REG.hm_recurso = 5003032	
)AMTS