SELECT
"Ordem"
, "Cod/Rep"
, "Descrição dos Projetos SAP"
, "Diretoria Executiva"
, "Divisão"
, "Hierarquia de Priorização"	
, "Tipo Projeto"
, "STATUS PRIORIZACAO"
, "GUESS CAPEX"
, "GUESS OPEX"
, "GUESS RECURSOS INTERNOS"
, "Classificação"
, "> 500K ?"
, "VALOR_DEMANDA"
, "Tipo de Projeto"
, "Criação Ord"
, "Encer. Ord"
, "Data do Último Lançamento"
, "Duração em Meses"
, "Cl. Custo"
, "Orçamento Capex"
, "Orçamento Opex"	
, "Orçamento Global"
, "Orçamento Indireto Recursos Internos"
, "Realizado" "Gastos em 2016"
, "Gasto Recursos anos anteriores"
, "Gasto Recursos Internos 2016"
, ("Orçado" - "Realizado") "Disponível Contabilidade Sem Compr."
, "Comprometido"
, ("Orçado" - "Comprometido" - "Realizado") "Disponível"
, "Status"
, "Área (TI)"
, "Projetado do ano" "Projetado do Disponível em 2016"
, ("Projetado do ano" + "Comprometido do ano") "Projetado em 2016"
, "Comprometido Após Ano" "Comprometido Após 2016"
, "Projetado Após Ano" "Projetado do Disponível Após 2016"
, ("Comprometido Após Ano" + "Projetado Após Ano") "Projetado após 2016"
, CASE
	WHEN ("Orçado" - "Comprometido") < 0 THEN 'Valor Projetado acima do Disponível'
	ELSE 'Valor Projetado dentro do Disponível'
	END "Status do Orçamento"
, CASE
	WHEN ("Orçado" - "Comprometido") < 0 THEN ("Orçado" - "Comprometido")
	ELSE 0
	END "Valor projetado não aprovado"
, CASE
	WHEN ("Orçado" - "Comprometido") > 0 THEN ("Orçado" - "Comprometido")
	ELSE 0
	END "Valor orçado não projetado"
, "Previsão de Data Go Live"
, "E-mail"
, ("Realizado Ano Corrente" + "Gasto Recursos Internos 2016") "VALOR GASTO 2016"
, "Projetado do ano" "VALOR A GASTAR"
, ("Orçamento de RI" - "Gastos de RI") "PREVISÃO FOLHA FUTURA"
, ("Projetado do ano" + ("Orçamento de RI" - "Gastos de RI")) "Total Valor a Gastar"
, ("Realizado Ano Corrente" + ("Projetado do ano" + ("Orçamento de RI" - "Gastos de RI"))) "TOTAL ORÇAMENTO"
, "Externo após ano corrente" "Externo após 2016"
, "Interno após ano corrente" "Interno após 2016"
, ("Externo após ano corrente" + "Interno após ano corrente") "Total após 2016"
, ("Realizado Ano Corrente" + "Externo após ano corrente") "Orçamento Total Previsto"
, ("Realizado Ano Corrente" + "Projetado do ano") "Realizado  Abertura gráfica"
, ("Realizado Ano Corrente" + "Projetado do ano") "Diferença"

FROM
(

	SELECT
		OSAP.hm_ordem_sap "Ordem"
		, INVI.CODE "Cod/Rep"
		, INVI.NAME "Descrição dos Projetos SAP"
		, DIR_EXEC.NAME "Diretoria Executiva"
		, DIVISAO.NAME "Divisão"
		, HIERARQUIA_PRI.NAME "Hierarquia de Priorização"	
		, OCINV.hm_tipo_projeto	"Tipo Projeto"
		, INVI.STAGE_CODE "STATUS PRIORIZACAO"
		, IDEA_FFIN.PLANNED_CST_CAPITAL_TOTAL "GUESS CAPEX"
		, IDEA_FFIN.PLANNED_CST_OPERATING_TOTAL "GUESS OPEX"
		, IDEA_OCINV.hm_cust_int "GUESS RECURSOS INTERNOS"
		, CLASSIFICACAO.NAME "Classificação"
		, CASE
			WHEN CUSTO_DEMANDA.NAME = 'Demanda > 500K' THEN 'Sim'
			WHEN CUSTO_DEMANDA.NAME = 'Maior que 500K' THEN 'Sim'
			ELSE 'Não'
			END "> 500K ?"
		, OCINV.hm_valor_demand "VALOR_DEMANDA"
		, TIPO_CUSTO.NAME "Tipo de Projeto"
		, OSAP.hm_criacao "Criação Ord"
		, OSAP.hm_encerramento "Encer. Ord"
		, OSAP.hm_ultimo_lanc "Data do Último Lançamento"
		, CASE 
			WHEN DATEDIFF(MONTH, GETDATE(), BIZ.START_DATE) <= 0 THEN 0
			ELSE DATEDIFF(MONTH, GETDATE(), BIZ.START_DATE) 
			END "Duração em Meses"
		, OCPRJ.hm_centro_custo "Cl. Custo"
		, FFIN.PLANNED_CST_CAPITAL_TOTAL "Orçamento Capex"
		, FFIN.PLANNED_CST_OPERATING_TOTAL "Orçamento Opex"	
		, FFIN.PLANNED_CST_TOTAL "Orçamento Global"
		, OCINV.hm_cust_int "Orçamento Indireto Recursos Internos"
		,	(
				SELECT	
					SUM(PV.TOTALCOST)
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'

				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE()) - 1
			) "Gasto Recursos anos anteriores"
		,	(
				SELECT	
					SUM(PV.TOTALCOST)
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'

				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE())		
			) "Gasto Recursos Internos 2016"
		,	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'comprometido'
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap		
			) "Comprometido"
		,	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap		
			) "Orçado"
		,	(
				SELECT 
					SUM(PV.TOTALCOST) 
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.USER_LOV1 = OSAP.hm_ordem_sap	
			) "Realizado"
		,	(
				SELECT 
					SUM(PV.TOTALCOST) 
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.USER_LOV1 = OSAP.hm_ordem_sap
					AND DATEPART(YEAR,PW.ENTRYDATE) = DATEPART(YEAR,GETDATE())						
			) "Realizado Ano Corrente"
		, STATUS.NAME "Status"
		, AREA_TI.NAME "Área (TI)"
		,	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE())
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap		
			) "Projetado do ano"
		,   (
				SELECT	
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'comprometido'
					AND DATEPART(YEAR,FP_COST.START_DATE) = DATEPART(YEAR,GETDATE())
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap
			) "Comprometido do ano"
		, 	(
				SELECT	
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'
					AND DATEPART(YEAR,FP_COST.START_DATE) >= DATEPART(YEAR,GETDATE()) + 1
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap
			) "Projetado Após Ano"
		, 	(
				SELECT	
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND hm_tipo_plano_custo = 'comprometido'
					AND DATEPART(YEAR,FP_COST.START_DATE) >= DATEPART(YEAR,GETDATE()) + 1
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap
			) "Comprometido Após Ano"
		, OCPRJ.data_go_live "Previsão de Data Go Live"
		, USR.EMAIL_ADDRESS "E-mail"
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap					
			) "Orçamento de RI"
		,	(
				SELECT	
					SUM(PV.TOTALCOST)
				FROM 
					NIKU.PPA_WIP PW 
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'

				WHERE
					PW.INVESTMENT_ID = INVI.ID
					AND PW.RESOURCE_CLASS = 'RECINT'
					AND PW.USER_LOV1 = OSAP.hm_ordem_sap
			) "Gastos de RI"
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'
					AND RES_CLASS.RESOURCE_CLASS != 'RECINT'
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap
					AND DATEPART(YEAR,FP_COST.START_DATE) >= DATEPART(YEAR,GETDATE()) + 1					
			) "Externo após ano corrente"
		, 	(
				SELECT
					SUM(ISNULL(ROUND((DATEDIFF(DAY,FP_COST.START_DATE,FP_COST.FINISH_DATE)*FP_COST.SLICE),0),0))
				FROM
					NIKU.FIN_PLANS FIN_PLAN
					LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD on FIN_PLAN.ID = FPD.PLAN_ID
					LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST on FIN_PLAN.ID = OCA_COST.ID
					LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
					LEFT JOIN NIKU.CMN_LOOKUPS_V LOV1 ON LOV1.ID = FPD.LOV1_ID  AND LOV1.LANGUAGE_CODE = 'pt' AND LOV1.LOOKUP_TYPE = 'PRTIMEENTRY_USER_LOV1'
					LEFT JOIN NIKU.PAC_FOS_RESOURCE_CLASS RES_CLASS ON RES_CLASS.ID = FPD.RESOURCE_CLASS_ID
				WHERE
					FIN_PLAN.OBJECT_ID = INVI.ID
					AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
					AND hm_tipo_plano_custo = 'planejado'
					AND RES_CLASS.RESOURCE_CLASS = 'RECINT'
					AND LOV1.LOOKUP_CODE = OSAP.hm_ordem_sap
					AND DATEPART(YEAR,FP_COST.START_DATE) >= DATEPART(YEAR,GETDATE()) + 1					
			) "Interno após ano corrente"
	FROM
		NIKU.INV_INVESTMENTS INVI
		JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN NIKU.ODF_CA_INV IDEA_OCINV ON INVI.IDEA_ID = IDEA_OCINV.ID
		JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
		JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
		JOIN NIKU.FIN_FINANCIALS FFIN ON INVI.ID = FFIN.ID
		JOIN NIKU.FIN_FINANCIALS IDEA_FFIN ON IDEA_FFIN.ID = INVI.IDEA_ID
		LEFT JOIN NIKU.FIN_PLANS FIN_PLAN ON FIN_PLAN.OBJECT_ID = INVI.ID AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
		JOIN NIKU.BIZ_COM_PERIODS BIZ ON BIZ.ID = FIN_PLAN.END_PERIOD_ID
		JOIN NIKU.CMN_SEC_USERS USR ON USR.ID = INVI.MANAGER_ID
		LEFT JOIN NIKU.ODF_CA_HM_ORDEM_SAP OSAP ON OSAP.ODF_PARENT_ID = INVI.ID
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIR_EXEC ON DIR_EXEC.LOOKUP_CODE = OCINV.HM_NOME_DIRETORIA AND DIR_EXEC.LANGUAGE_CODE = 'pt' AND DIR_EXEC.LOOKUP_TYPE = 'HM_LKP_NOME_DIRETORIA' 
		LEFT JOIN NIKU.CMN_LOOKUPS_V DIVISAO ON DIVISAO.LOOKUP_CODE = OCINV.HM_DIVISAO AND DIVISAO.LANGUAGE_CODE = 'pt' AND DIVISAO.LOOKUP_TYPE = 'HM_LKP_DIVISAO'
		LEFT JOIN NIKU.CMN_LOOKUPS_V HIERARQUIA_PRI ON HIERARQUIA_PRI.LOOKUP_CODE = INVI.GOAL_CODE AND HIERARQUIA_PRI.LANGUAGE_CODE = 'pt' AND HIERARQUIA_PRI.LOOKUP_TYPE = 'INVESTMENT_GOAL_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V AREA_TI ON AREA_TI.LOOKUP_CODE = OCINV.HM_AREA_TI AND AREA_TI.LANGUAGE_CODE = 'pt' AND AREA_TI.LOOKUP_TYPE = 'AREAS_TI'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CLASSIFICACAO ON CLASSIFICACAO.LOOKUP_CODE = OCPRJ.OBJ_REQUEST_TYPE AND CLASSIFICACAO.LANGUAGE_CODE = 'pt' AND CLASSIFICACAO.LOOKUP_TYPE = 'OBJ_IDEA_PROJECT_TYPE'
		LEFT JOIN NIKU.CMN_LOOKUPS_V CUSTO_DEMANDA ON CUSTO_DEMANDA.LOOKUP_CODE = OCPRJ.CUSTO_DEMANDA AND CUSTO_DEMANDA.LANGUAGE_CODE = 'pt' AND CUSTO_DEMANDA.LOOKUP_TYPE = 'CUSTO_DEMANDA'
		LEFT JOIN NIKU.CMN_LOOKUPS_V STATUS ON STATUS.LOOKUP_CODE = OCINV.HM_SITUACAO_AGRUP AND STATUS.LANGUAGE_CODE = 'pt' AND STATUS.LOOKUP_TYPE = 'HM_LKP_SITUACAO_AGRUP'
		LEFT JOIN NIKU.CMN_LOOKUPS_V TIPO_CUSTO ON TIPO_CUSTO.LOOKUP_CODE = PMPRJ.COST_TYPE  AND TIPO_CUSTO.LANGUAGE_CODE = 'pt' AND TIPO_CUSTO.LOOKUP_TYPE = 'LOOKUP_FIN_COSTTYPECODE'
		
	WHERE
		INVI.ID = 5134002

)FINANCIAL

ORDER BY
	"Cod/Rep" ASC
	, "Ordem" ASC