SELECT

TOTAL_PRJ.CLASSE CATEGORIA
, PRJ_TI.VALOR PROJETOS_DE_TI
, MELHORIAS_PRJ.VALOR PROJETOS_MELHORIAS
, NOVOS_NEG.VALOR NOVOS_NEGOCIOS
, TOTAL_PRJ.VALOR TOTAL
, TOTAL_PRJ.PCT_REALIZADO


FROM

(SELECT 
 TRANSCLASS, CLASSE, VALOR, VALOR/TOTAL PCT_REALIZADO

FROM 
(SELECT ISNULL(SUM(PV.TOTALCOST),0) VALOR
	, CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END CLASSE 
	, TC.TRANSCLASS 
	, (SELECT ISNULL(SUM(PV.TOTALCOST),0) VALOR
FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
WHERE INVI.ODF_OBJECT_CODE = 'project' ) TOTAL
FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
WHERE INVI.ODF_OBJECT_CODE = 'project'
AND PW.ENTRYDATE < = (SELECT  MAX(hm_data_corte) FROM NIKU.odf_ca_hm_data_relatorio WHERE hm_aprovado = 1)
GROUP BY CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END
, TC.TRANSCLASS
) TOTAL) TOTAL_PRJ

FULL OUTER JOIN

(SELECT 
 TRANSCLASS, CLASSE, VALOR

FROM 
(SELECT ISNULL(SUM(PV.TOTALCOST),0) VALOR
	,TC.DESCRIPTION CLASSE
	,TC.TRANSCLASS 
	
FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
WHERE INVI.ODF_OBJECT_CODE = 'project'
AND OCINV.hm_class_inv = 'novos_negocios'
AND PW.ENTRYDATE < = (SELECT  MAX(hm_data_corte) FROM NIKU.odf_ca_hm_data_relatorio WHERE hm_aprovado = 1)
GROUP BY TC.DESCRIPTION
, TC.TRANSCLASS
) NEGOCIOS ) NOVOS_NEG
ON TOTAL_PRJ.TRANSCLASS = NOVOS_NEG.TRANSCLASS

FULL OUTER JOIN 

(SELECT 
 TRANSCLASS, CLASSE, VALOR

FROM 
(SELECT ISNULL(SUM(PV.TOTALCOST),0) VALOR
	,CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END CLASSE
	,TC.TRANSCLASS 
	
FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
WHERE INVI.ODF_OBJECT_CODE = 'project'
AND OCINV.hm_class_inv = 'projeto_ti'
AND PW.ENTRYDATE < = (SELECT  MAX(hm_data_corte) FROM NIKU.odf_ca_hm_data_relatorio WHERE hm_aprovado = 1)
GROUP BY CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END
, TC.TRANSCLASS
) PROJETOS_TI )PRJ_TI
ON TOTAL_PRJ.TRANSCLASS = PRJ_TI.TRANSCLASS

FULL OUTER JOIN 

(SELECT 
 TRANSCLASS, CLASSE, VALOR

FROM 
(SELECT ISNULL(SUM(PV.TOTALCOST),0) VALOR
	,CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END CLASSE
	,TC.TRANSCLASS 
	
FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
JOIN NIKU.ODF_CA_PROJECT OCPRJ ON INVI.ID = OCPRJ.ID
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
WHERE INVI.ODF_OBJECT_CODE = 'project'
AND OCINV.hm_class_inv = 'projetos_melhorias'
AND PW.ENTRYDATE < = (SELECT  MAX(hm_data_corte) FROM NIKU.odf_ca_hm_data_relatorio WHERE hm_aprovado = 1)
GROUP BY CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END
, TC.TRANSCLASS
) MELHORIAS) MELHORIAS_PRJ
ON TOTAL_PRJ.TRANSCLASS = MELHORIAS_PRJ.TRANSCLASS

ORDER BY TOTAL DESC