SELECT 
TOTAL.TIPO
, OPERACOES.CUSTO AS OPERACAO
, PROJETOS.CUSTO PROJETO
, TOTAL.CUSTO TOTAL

FROM
(SELECT 'CAPEX' TIPO
					,ISNULL(SUM(PV.TOTALCOST),0) CUSTO
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = INVI.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PMPRJ.COST_TYPE = 'CAPITAL'
UNION 

SELECT 'OPEX' TIPO
					,ISNULL(SUM(PV.TOTALCOST),0) CUSTO
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = INVI.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PMPRJ.COST_TYPE = 'OPERATING'
UNION 					
SELECT 'PESSOAL' TIPO
, 0 CUSTO) TOTAL 
JOIN
(SELECT 'CAPEX' TIPO
					,ISNULL(SUM(PV.TOTALCOST),0) CUSTO
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = INVI.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PMPRJ.COST_TYPE = 'CAPITAL'
					AND INVI.ODF_OBJECT_CODE = 'other'
UNION 

SELECT 'OPEX' TIPO
					,ISNULL(SUM(PV.TOTALCOST),0) CUSTO
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = INVI.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PMPRJ.COST_TYPE = 'OPERATING'
					AND INVI.ODF_OBJECT_CODE = 'other'
UNION 					
SELECT 'PESSOAL' TIPO
, 0 CUSTO					
) OPERACOES ON OPERACOES.TIPO = TOTAL.TIPO
JOIN 
(SELECT 'CAPEX' TIPO
					,ISNULL(SUM(PV.TOTALCOST),0) CUSTO
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = INVI.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PMPRJ.COST_TYPE = 'CAPITAL'
					AND INVI.ODF_OBJECT_CODE = 'project'
UNION 

SELECT 'OPEX' TIPO
					,ISNULL(SUM(PV.TOTALCOST),0) CUSTO
				FROM 
					NIKU.INV_INVESTMENTS INVI
					JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON PMPRJ.ID = INVI.ID
					JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
					LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
				WHERE
					PMPRJ.COST_TYPE = 'OPERATING'
					AND INVI.ODF_OBJECT_CODE = 'project'
UNION 					
SELECT 'PESSOAL' TIPO
, 0 CUSTO) PROJETOS ON OPERACOES.TIPO = PROJETOS.TIPO

