SELECT 
	CASE 
		WHEN ORCADO.CLASSE IS NULL 
		THEN REALIZADO.CLASSE 
		ELSE ORCADO.CLASSE 
	END CATEGORIA
	, SUM(ISNULL(ORCADO.VALOR,0)) ORCADO
	, SUM(ISNULL(REALIZADO.VALOR,0)) REALIZADO
	, SUM(ISNULL(ORCADO.VALOR,0))-SUM(ISNULL(REALIZADO.VALOR,0)) A_REALIZAR
FROM

(SELECT SUM(ISNULL(ROUND((DATEDIFF(DAY, FP_COST.START_DATE, FP_COST.FINISH_DATE) * FP_COST.SLICE), 0), 0)) VALOR
	, CASE WHEN RC.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END CLASSE
	, TC.TRANSCLASS

FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.FIN_PLANS FIN_PLAN ON FIN_PLAN.OBJECT_ID = INVI.ID
LEFT JOIN NIKU.FIN_COST_PLAN_DETAILS FPD ON FIN_PLAN.ID = FPD.PLAN_ID
LEFT JOIN NIKU.ODF_CA_COSTPLAN OCA_COST ON FIN_PLAN.ID = OCA_COST.ID
LEFT JOIN NIKU.ODF_SSL_CST_DTL_COST FP_COST ON FPD.ID = FP_COST.PRJ_OBJECT_ID
JOIN NIKU.TRANSCLASS TC ON TC.ID = FPD.TRANSACTION_CLASS_ID
JOIN NIKU.PAC_FOS_RESOURCE_CLASS RC ON RC.ID = FPD.RESOURCE_CLASS_ID
WHERE INVI.ODF_OBJECT_CODE = 'project'
	AND OCA_COST.hm_tipo_plano_custo = 'planejado'
	AND FIN_PLAN.IS_PLAN_OF_RECORD = 1
GROUP BY CASE WHEN RC.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END
, TC.TRANSCLASS
) ORCADO

FULL OUTER JOIN 

(
SELECT ISNULL(SUM(PV.TOTALCOST),0) VALOR
	,CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END CLASSE
	,TC.TRANSCLASS 
FROM NIKU.INV_INVESTMENTS INVI
JOIN NIKU.PAC_MNT_PROJECTS PMPRJ ON INVI.ID = PMPRJ.ID
JOIN NIKU.PPA_WIP PW ON PW.INVESTMENT_ID = INVI.ID
LEFT JOIN NIKU.PPA_WIP_VALUES PV ON PW.TRANSNO = PV.TRANSNO AND PV.CURRENCY_TYPE = 'HOME'
JOIN NIKU.TRANSCLASS TC ON TC.TRANSCLASS = PW.TRANSCLASS
WHERE INVI.ODF_OBJECT_CODE = 'project'

GROUP BY CASE WHEN PW.RESOURCE_CLASS = 'RECINT' THEN 'Pessoal' ELSE TC.DESCRIPTION END
, TC.TRANSCLASS
) REALIZADO ON ORCADO.TRANSCLASS = REALIZADO.TRANSCLASS

WHERE ISNULL(ORCADO.VALOR,0) > 0 OR ISNULL(REALIZADO.VALOR,0) > 0

GROUP BY CASE 
		WHEN ORCADO.CLASSE IS NULL 
		THEN REALIZADO.CLASSE 
		ELSE ORCADO.CLASSE 
	END
ORDER BY ORCADO DESC, REALIZADO DESC