SELECT INVI.NAME
, 'Q' || TO_CHAR(TO_DATE(INVI.SCHEDULE_FINISH), 'Q') || ' ' || TO_CHAR(TO_DATE(INVI.SCHEDULE_FINISH), 'YYYY') LAUNCH_QUARTER
, BU.NAME BU
, SUM(Y1BEN.SLICE) Y1_SALES_FORECAST
, SUM(Y2BEN.SLICE) Y2_SALES_FORECAST
, SUM(Y3BEN.SLICE) Y3_SALES_FORECAST

FROM INV_INVESTMENTS INVI
JOIN ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
JOIN INV_PROJECTS INVP ON INVI.ID = INVP.PRID
LEFT JOIN CMN_LOOKUPS_V BU ON BU.LOOKUP_CODE = OCINV.SAN_BU 
  AND BU.LOOKUP_TYPE = 'SAN_LKP_BU' 
  AND BU.LANGUAGE_CODE = 'en'
LEFT JOIN FIN_PLANS Y1 ON Y1.OBJECT_ID = INVI.ID
LEFT JOIN FIN_BENEFIT_PLAN_DETAILS Y1D ON Y1D.PLAN_ID = Y1.ID
LEFT JOIN ODF_SSL_BFT_DTL_BFT Y1BEN ON Y1BEN.PRJ_OBJECT_ID = Y1D.ID
LEFT JOIN FIN_PLANS Y2 ON Y2.OBJECT_ID = INVI.ID
LEFT JOIN FIN_BENEFIT_PLAN_DETAILS Y2D ON Y2D.PLAN_ID = Y2.ID
LEFT JOIN ODF_SSL_BFT_DTL_BFT Y2BEN ON Y2BEN.PRJ_OBJECT_ID = Y2D.ID
LEFT JOIN FIN_PLANS Y3 ON Y3.OBJECT_ID = INVI.ID
LEFT JOIN FIN_BENEFIT_PLAN_DETAILS Y3D ON Y3D.PLAN_ID = Y3.ID
LEFT JOIN ODF_SSL_BFT_DTL_BFT Y3BEN ON Y3BEN.PRJ_OBJECT_ID = Y3D.ID

WHERE INVI.IS_ACTIVE = 1
AND INVP.IS_TEMPLATE = 0

--AND INVI.SCHEDULE_FINISH >= 
--AND INVI.SCHEDULE_FINISH <=

GROUP BY
INVI.NAME
, 'Q' || TO_CHAR(TO_DATE(INVI.SCHEDULE_FINISH), 'Q') || ' ' || TO_CHAR(TO_DATE(INVI.SCHEDULE_FINISH), 'YYYY') 
, BU.NAME 