SELECT
THEME
, PC
, LISTAGG(KI,'/') WITHIN GROUP (ORDER BY TSK_ORDER) KI
, LISTAGG(APRIL,'/') WITHIN GROUP (ORDER BY TSK_ORDER) APRIL
, LISTAGG(MAY,'/') WITHIN GROUP (ORDER BY TSK_ORDER) MAY
, LISTAGG(JUNE,'/') WITHIN GROUP (ORDER BY TSK_ORDER) JUNE
, LISTAGG(JULY,'/') WITHIN GROUP (ORDER BY TSK_ORDER) JULY
, LISTAGG(AUGUST,'/') WITHIN GROUP (ORDER BY TSK_ORDER) AUGUST
, LISTAGG(SEPTEMBER,'/') WITHIN GROUP (ORDER BY TSK_ORDER) SEPTEMBER
, LISTAGG(OCTOBER,'/') WITHIN GROUP (ORDER BY TSK_ORDER) OCTOBER
, LISTAGG(NOVEMBER,'/') WITHIN GROUP (ORDER BY TSK_ORDER) NOVEMBER
, LISTAGG(DECEMBER,'/') WITHIN GROUP (ORDER BY TSK_ORDER) DECEMBER
, LISTAGG(JANUARY,'/') WITHIN GROUP (ORDER BY TSK_ORDER) JANUARY
, LISTAGG(FEBRUARY,'/') WITHIN GROUP (ORDER BY TSK_ORDER) FEBRUARY
, LISTAGG(MARCH,'/') WITHIN GROUP (ORDER BY TSK_ORDER) MARCH
, LISTAGG(KIP,'/') WITHIN GROUP (ORDER BY TSK_ORDER) KIP

FROM
(
	SELECT DISTINCT
		THEME
		, INV_ID  
		, CASE WHEN KI = 1 THEN TSK END KI
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 4 THEN TSK ELSE '' END APRIL
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 5 THEN TSK ELSE '' END MAY
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 6 THEN TSK ELSE '' END JUNE
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 7 THEN TSK ELSE '' END JULY
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 8 THEN TSK ELSE '' END AUGUST
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 9 THEN TSK ELSE '' END SEPTEMBER
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 10 THEN TSK ELSE '' END OCTOBER
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 11 THEN TSK ELSE '' END NOVEMBER
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 12 THEN TSK ELSE '' END DECEMBER
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 1 THEN TSK ELSE '' END JANUARY
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 2 THEN TSK ELSE '' END FEBRUARY
		, CASE WHEN KI = 0 AND TO_CHAR(MES,'MM') = 3 THEN TSK ELSE '' END MARCH
		, CASE WHEN KI = 2 THEN TSK END KIP
		, PC
   		, PC_ORDER
		, DATA_TAREFA
		, CASE 
			WHEN TSK = 'U0' THEN 10
			WHEN TSK = 'U1' THEN 20
			WHEN TSK = 'J0' THEN 30
			WHEN TSK = 'J1' THEN 40
			WHEN TSK = 'J2' THEN 50
			WHEN TSK = 'J3' THEN 60
			WHEN TSK = 'J4' THEN 70
			WHEN TSK = 'J5' THEN 80
			WHEN TSK = 'P0' THEN 90
			ELSE 100
			END TSK_ORDER
	FROM
	(
		SELECT DISTINCT 
			INVI.NAME THEME
			, INVI.ID INV_ID
			, OCINV.HON_AREA OWNER
			, SUBSTR(TSK,1,2) TSK
			, PERIODS.START_DATE MES
			, MES_INI DATA_TAREFA
			, CASE				
				WHEN 
					PERIODS.START_DATE >= PF.DT_INICIO_KI_ANT
					AND PERIODS.START_DATE <= PF.DT_TERMINO_KI_ANT
					THEN 1
				WHEN
					PC = 'ACTUAL' 
					AND PERIODS.START_DATE >= PF.DT_INICIO_KI_ATUAL
					AND PERIODS.START_DATE <= TRUNC($P{data_referencia},'MONTH')
					THEN 0 
				WHEN
					PC != 'ACTUAL'
					AND PERIODS.START_DATE >= PF.DT_INICIO_KI_ATUAL
					AND PERIODS.START_DATE <= PF.DT_TERMINO_KI_ATUAL
					THEN 0
				WHEN
					PERIODS.START_DATE >= PF.DT_INICIO_KI_PROX
					AND PERIODS.START_DATE <= PF.DT_TERMINO_KI_PROX
					THEN 2
				ELSE NULL 
				END KI
			, PC
			, PC_ORDER
		FROM
		(
			SELECT DISTINCT
				INVI.ID INV_ID
				, SUBSTR(TSK.PRNAME,1,2) TSK
				, MIN(BASE_DETAILS.START_DATE) MES_INI 
				, MAX(BASE_DETAILS.FINISH_DATE) MES_FIM
				, 'ORB' PC
				, 10 PC_ORDER
			FROM 
				INV_INVESTMENTS INVI
				LEFT JOIN PRTASK TSK ON INVI.ID = TSK.PRPROJECTID  AND SUBSTR(TSK.PRNAME,1,2) IN ('U0','U1','J0','J1','J2','J3','J4','J5','P0')
				LEFT JOIN PRJ_BASELINES BASELINE ON BASELINE.PROJECT_ID = TSK.PRPROJECTID 
				LEFT JOIN ODF_CA_BASELINE OCB ON BASELINE.ID = OCB.ID
				LEFT JOIN PRJ_BASELINE_DETAILS BASE_DETAILS ON BASE_DETAILS.OBJECT_ID = TSK.PRID AND BASE_DETAILS.BASELINE_ID = BASELINE.ID AND BASE_DETAILS.BASELINE_ID = OCB.ID
			WHERE
				(BASELINE.ID IS NULL OR BASELINE.ID = (SELECT MAX(BAS.ID) FROM PRJ_BASELINES BAS JOIN ODF_CA_BASELINE OBAS ON OBAS.ID = BAS.ID WHERE BAS.PROJECT_ID = INVI.ID AND OBAS.HON_ORB = 1))
			GROUP BY
				INVI.ID
				, SUBSTR(TSK.PRNAME,1,2)

			UNION 

			SELECT DISTINCT
				INVI.ID INV_ID
				, SUBSTR(TSK.PRNAME,1,2) TSK
				, MIN(BASE_DETAILS.START_DATE) MES_INI 
				, MAX(BASE_DETAILS.FINISH_DATE) MES_FIM
				, 'PLAN' PC
				, 20 PC_ORDER
			FROM 
				INV_INVESTMENTS INVI
				LEFT JOIN PRTASK TSK ON INVI.ID = TSK.PRPROJECTID  AND SUBSTR(TSK.PRNAME,1,2) IN ('U0','U1','J0','J1','J2','J3','J4','J5','P0')
				LEFT JOIN PRJ_BASELINES BASELINE ON BASELINE.PROJECT_ID = TSK.PRPROJECTID AND BASELINE.IS_CURRENT = 1 
				LEFT JOIN PRJ_BASELINE_DETAILS BASE_DETAILS ON BASE_DETAILS.OBJECT_ID = TSK.PRID AND BASE_DETAILS.IS_CURRENT = 1 AND BASE_DETAILS.BASELINE_ID = BASELINE.ID
			GROUP BY
				INVI.ID
				, SUBSTR(TSK.PRNAME,1,2)

			UNION
			
			SELECT DISTINCT
				INVI.ID INV_ID
				, SUBSTR(TSK.PRNAME,1,2) TSK
				, MIN(TSK.PRSTART) MES_INI 
				, MAX(TSK.PRFINISH) MES_FIM
				, 'ACTUAL' PC
				, 30 PC_ORDER
			FROM 
				INV_INVESTMENTS INVI 
				LEFT JOIN PRTASK TSK ON INVI.ID = TSK.PRPROJECTID AND SUBSTR(TSK.PRNAME,1,2) IN ('U0','U1','J0','J1','J2','J3','J4','J5','P0') 
			GROUP BY
				INVI.ID
				, SUBSTR(TSK.PRNAME,1,2)
		)TASKS
		JOIN INV_INVESTMENTS INVI ON INVI.ID = TASKS.INV_ID
		JOIN ODF_CA_INV OCINV ON INVI.ID = OCINV.ID
		LEFT JOIN BIZ_COM_PERIODS PERIODS ON ((TRUNC(TASKS.MES_INI,'MONTH') <= PERIODS.START_DATE  AND TRUNC(TASKS.MES_FIM,'MONTH') >= PERIODS.START_DATE ) ) AND PERIODS.PERIOD_TYPE = 'MONTHLY'
		LEFT JOIN
			(
				SELECT
					PF.NAME KI,
					(SELECT dt_inicio FROM ODF_CA_HON_PER_FISCAIS WHERE NAME = PF.hon_prev_ki) DT_INICIO_KI_ANT,
					(SELECT dt_termino FROM ODF_CA_HON_PER_FISCAIS WHERE NAME = PF.hon_prev_ki) DT_TERMINO_KI_ANT,
					PF.dt_inicio DT_INICIO_KI_ATUAL,
					PF.dt_termino DT_TERMINO_KI_ATUAL,
					(SELECT dt_inicio FROM ODF_CA_HON_PER_FISCAIS WHERE NAME = PF.hon_next_ki) DT_INICIO_KI_PROX,
					(SELECT dt_termino FROM ODF_CA_HON_PER_FISCAIS WHERE NAME = PF.hon_next_ki) DT_TERMINO_KI_PROX
				FROM
					ODF_CA_HON_PER_FISCAIS PF
				WHERE
					$P{data_referencia} >= PF.dt_inicio AND $P{data_referencia} <= PF.dt_termino
			)PF ON 1=1
	)	
)
WHERE 
	INV_ID = $P{INV_ID}

GROUP BY
	THEME
	, PC
	, PC_ORDER

ORDER BY
	PC_ORDER ASC